### ISSUE TITLE
[Major Issue] Prison overrides protection plugins

### ISSUE THREAD

**Issue by astr1al** [SirFaizdat/Prison#100]
Hello SirFaizdat, I would like to report an issue with Prison 3.0.0 which allows players to break protected chests w/ Lockette, and also allows players to break area protection stones from the PreciousStones plugin. Can confirm the issue is caused by latest version of prison. I am running on Spigot 1.8.8. Please let me know if you need any further details.

**Comment by SirFaizdat** [comment]
Confirmed major bug, working on an emergency patch now.

**Comment by SirFaizdat** [comment]
Fixed in v2.1.6. Let me know if it solves your problem.

**Comment by astr1al** [comment]
Looks good, thanks for the quick fix. :)

**Comment by SirFaizdat** [comment]
Thanks for pointing out such an awful bug :) I hope no one got griefed because of this :(

**Comment by astr1al** [comment]
There were a few casualties, butt we live to fight another day.
