### ISSUE TITLE
Ranks Bug

### ISSUE THREAD

**Issue by cookiejoostxd** [SirFaizdat/Prison#101]
My ranks are setup that is good but i got 1 issue.
Whenever they rankup they don't go higher then rank B.
How can i fix this?

**Comment by SirFaizdat** [comment]
You can fix this by making sure each rank inherits its predecessor in your groups plugin.

**Comment by cookiejoostxd** [comment]
Like adding parents or just do /mangaddi (using groupmanager).
Because i already have them with /mangaddi
B got A
C got B
D got C
E got D
F got E 
etc....

**Comment by Bammie05** [comment]
i type this command /prisonranks add Chicken $1500 &6&lChicken and it says That rank does not exist! D:

**Comment by SirFaizdat** [comment]
@Bammie05 You have to create it in your groups plugin first
@cookiejoostxd Hmmmm... the ranks are ordered by either the permissions/groups plugin you have or the order in which you added them to Prison. Perhaps that information may help?

**Comment by cookiejoostxd** [comment]
I first added A, then b, then c etc.
So i already done that

**Comment by cookiejoostxd** [comment]
@Bammie05 Did you create the rank with your group plugin?

**Comment by SirFaizdat** [comment]
Can you send me both your Prison folder and your GroupManager folder? Just zip (compress) them and drag+drop them here.

**Comment by cookiejoostxd** [comment]
Isn't supported

**Comment by bennyb1971** [comment]
i have the same issue with the ranks, and indeed zip files arent supported.
But all my ranks are setup in pex, inheriting from the previous rank

**Comment by bennyb1971** [comment]
We need Prison 3 badly :p

**Comment by bennyb1971** [comment]
will upload a screenshot
![schermafdruk 2015-11-23 17 33 02](https://cloud.githubusercontent.com/assets/15984199/11342588/5f08a576-9208-11e5-9d2f-a41ab033feb2.png)
![schermafdruk 2015-11-23 17 31 51](https://cloud.githubusercontent.com/assets/15984199/11342589/5f08ce5c-9208-11e5-9a26-d878fcd0b571.png)

**Comment by SirFaizdat** [comment]
Prison v3.0 won't be released for a while, but Prison v2.2 certainly will, and it will definitely streamline the user interface.

What's inside ranksList.txt?

**Comment by bennyb1971** [comment]
nothing. Thats what triggered me that was something wrong, and why i started searching for answers.

**Comment by bennyb1971** [comment]
the strange thing is that when i do /rank, that it shows all the ranks. And i was wrong the ranklist.txt is this : 
![schermafdruk 2015-11-23 18 36 21](https://cloud.githubusercontent.com/assets/15984199/11344376/22c17094-9211-11e5-8f41-536be9276b1d.png)

**Comment by bennyb1971** [comment]
Also if the 2.2 version could have the warps for when mines reset would be awzsome ;) Happy to make a small donation for your effort too :)

**Comment by cookiejoostxd** [comment]
Some MC Players asking me why the server is whitelisted, it is because of the bug so can you try to look on my server whats wrong? 5.255.85.208:26522 I'll whitelist you, if SirFaizdat is your name you are whitelisted

**Comment by cookiejoostxd** [comment]
Bennyb you are dutch! Or geman i think dutch

**Comment by bennyb1971** [comment]
I'm from Belgium :)
Ugh this plugin not working is such a shame :(

**Comment by bennyb1971** [comment]
ok i dont know what i did, but i started ove and now i got working ranks!!!
Does the plugin have issues with other plugins??

**Comment by SirFaizdat** [comment]
Not that have been reported. Glad that it's working :)

**Comment by cookiejoostxd** [comment]
Well, for me its still not fixed

**Comment by SirFaizdat** [comment]
Sorry, I thought it was working for you too. Can you send me your files? The Prison folder and the GroupManager folder.

**Comment by cookiejoostxd** [comment]
https://gyazo.com/b98be3e049305b17e0ca3df6ccf7d6a7
https://gyazo.com/2e8cfbfffc4722eeba3210ade3a6521e
https://gyazo.com/313d18b26708e569214bcaa7add6e71a

**Comment by SirFaizdat** [comment]
I've seen a lot of problems with GroupManager, perhaps the same problem that's occurring with issue #107. I recommend switching to PermissionsEx, people have more success with that. I will try to add full support for plugins other than PermissionsEx in version 2.2.

**Comment by cookiejoostxd** [comment]
I will do that.

**Comment by SirFaizdat** [comment]
Let me know if it works.

**Comment by cookiejoostxd** [comment]
It does works with PEX
