### ISSUE TITLE
Mine/blocks

### ISSUE THREAD

**Issue by DatUltraWhale** [SirFaizdat/Prison#102]
I can get the ores but my players cant any help?

**Comment by SirFaizdat** [comment]
Can you please provide more details?

**Comment by DatUltraWhale** [comment]
Well I can make then mine and when I break ores like iron I get it but when my other players break the iron ore it drops nothing for them.

**Comment by DatUltraWhale** [comment]
So That's The Issue

**Comment by SirFaizdat** [comment]
What's your server IP? I'll come and try to fix it for you

**Comment by DatUltraWhale** [comment]
reypvp.serverminer.com

**Comment by DatUltraWhale** [comment]
thanks
