### ISSUE TITLE
Link ranks to a mine

### ISSUE THREAD

**Issue by Passyvrucht** [SirFaizdat/Prison#103]
Hey,

How can I make sure that people with the rank "A Mine" only in "Minea" can break and not in "MineB or "MineC"

**Comment by SirFaizdat** [comment]
I just removed this feature in v2.1.6 because it caused a huge bug. However, it will be re-added in v2.2. For now, look up "Adding ranks to WorldGuard" on Google ;)

**Comment by Passyvrucht** [comment]
Thank you! Whats the date when you release version 3.0?

**Comment by SirFaizdat** [comment]
Not for a few months now

**Comment by Passyvrucht** [comment]
Oke, thank you!
