### ISSUE TITLE
Mines

### ISSUE THREAD

**Issue by quack123456** [SirFaizdat/Prison#104]
Hi so i updated versions and my mines aren't listed in the server but I have the files in the ftp. Is there any way to put the mines back in the server. I tried putting the mines in the mine folder and it goes there but it doesn't show up in the server.

**Comment by SirFaizdat** [comment]
Is there any error in the console?

**Comment by quack123456** [comment]
http://pastebin.com/8nY8DYHb

**Comment by SirFaizdat** [comment]
Does it work if you create a new mine and then try to reload?

**Comment by quack123456** [comment]
No it doesnt show up It only shows the new mine i created.

**Comment by SirFaizdat** [comment]
When did you first start experiencing this issue?

**Comment by quack123456** [comment]
Just the day before

**Comment by SirFaizdat** [comment]
When you updated to v2.1.6?

**Comment by quack123456** [comment]
yea

**Comment by SirFaizdat** [comment]
Alright, this is a high-priority issue and I will fix it within 24 hours. Thanks for reporting!

**Comment by quack123456** [comment]
Thanksk

**Comment by quack123456** [comment]
Hi can you just notify me on this when you added the new version? Thanks

**Comment by SirFaizdat** [comment]
Is the world on the new server the same name as the world on the old server? If not, it needs to be.

**Comment by quack123456** [comment]
What are you asking exactly? The world is the same but when I updated the plugin it wouldn't load up the mines

**Comment by SirFaizdat** [comment]
The current save system is bad in that it has to be the *exact* same world in order to work. I was wondering if that was the problem, since your new mine that was created in the new server worked.

**Comment by quack123456** [comment]
I didn't the new mine in a new server. I just created the new mine in the same server but with the updated plugin.

**Comment by quack123456** [comment]
I didn't create the new mine in a new server is what I meant to say

**Comment by SirFaizdat** [comment]
Nonetheless, Prison v2.2 will fix it.

**Comment by quack123456** [comment]
When is that coming out?

**Comment by SirFaizdat** [comment]
Either after Spigot 1.9 or within 3 weeks - whichever comes first.

**Comment by quack123456** [comment]
So there is no way else to fix this for the time being. Because then I have to either wait for a month to get my friend's server up or remake all 30 mines

**Comment by SirFaizdat** [comment]
I'll help you with the mines, if you'd like.

**Comment by quack123456** [comment]
Okay sure maybe tomorrow. Good night

**Comment by quack123456** [comment]
Add me on skype and ill give you the ip to help me.My skype is grandmasterquack
