### ISSUE TITLE
[SUGGESTION] Items to Inventory

### ISSUE THREAD

**Issue by Passyvrucht** [SirFaizdat/Prison#105]
Hey!

I have a suggestion, Is it possible when people break example: Iron Ore that the ore directly to the inventory goes!

**Comment by SirFaizdat** [comment]
Approved to be added in v2.2.

**Comment by Badcholo** [comment]
I really like this idea with a permission node.

**Comment by SirFaizdat** [comment]
Added in commit 753e83b

I'd usually give you a development build, but there's a lot of broken stuff right now.

**Comment by SirFaizdat** [comment]
Closing as this is a Prison 2 request, and no more updates to Prison 2 will be made.
