### ISSUE TITLE
Ranks not working

### ISSUE THREAD

**Issue by popcorn9499** [SirFaizdat/Prison#107]
I was running prison 2.1.6
Ranks don't work at all. It just said "you have rankup to a!" It never said what the problem was it just wont go any higher.
For my permissions system i am using zpermissions. I tried resetting the config files and everything.
We running spigot 1.8.8

**Comment by SirFaizdat** [comment]
Make sure each rank inherits the last. I have no experience with zPermissiond, so I don't know exactly how to do that.

**Comment by popcorn9499** [comment]
i set the group to inherit the last group and its still not working. I had this working then all of the sudden it wouldn't work anymore. Nothing changed in that time too. I'm gonna try running a clean server no other plugins and seeing what happens then. Ill keep u posted on what happens.

**Comment by SirFaizdat** [comment]
Alright.

**Comment by popcorn9499** [comment]
is there any debug options that might help?

**Comment by popcorn9499** [comment]
or wait what about permissions that i might have missed?

**Comment by popcorn9499** [comment]
I have brought it down to weirdness of permissions. I dont see why its not working right with zperms when it works with pex? It might just be i dont know the permissions i need to use.

**Comment by SirFaizdat** [comment]
The fault probably lies with zPerms' connection with Vault.

**Comment by popcorn9499** [comment]
can you tell me what i can do to fix it?

**Comment by SirFaizdat** [comment]
I am currently returning home from a trip; I will be able to look into it with more detail when I get home.

**Comment by SirFaizdat** [comment]
I am currently returning home from a trip; I will be able to look into it with more detail when I get home.

**Comment by popcorn9499** [comment]
Ok thanks i hope you have a safe return trip home and that the trip was fun. Thanks for looking into this.

**Comment by SirFaizdat** [comment]
Thanks, it was, and you are are most welcome :)

**Comment by SirFaizdat** [comment]
(This is just a summary for the team's reference) The problem lies with Prison relying on Vault to fetch the next rank in the ladder, but zPerms fails to supply the next rank. Perhaps a ladder system can be introduced into Prison, that will not rely on Vault to fetch the next rank. The reporter has mentioned that it works fine with PEX, so the fault *most likely* lies with zPermissions.

**Comment by popcorn9499** [comment]
but why did it work awhile ago but not now? I didnt change any versions or nothing?

**Comment by SirFaizdat** [comment]
I don't know, but this seems to be the most likely source of the problem.

**Comment by popcorn9499** [comment]
are there any debug options in prison that might work to explain some things?

**Comment by popcorn9499** [comment]
also what are the permission nodes i need for prison?

**Comment by popcorn9499** [comment]
Just gonna say if u have any beta or alpha copies of this plugin that might have that a ladder system or something? I'd really like it if i could help out with these things. I'm really liking the support ive seen and everything

**Comment by SirFaizdat** [comment]
There aren't any debug options, that will be part of Prison v2.2. 

The permissions list is [http://dev.bukkit.org/bukkit-plugins/mcprison/pages/commands-permissions/](here). 

I will definitely provide alpha and beta versions and I will link you to them once they're ready.

**Comment by popcorn9499** [comment]
Ok so i had the all the correct permissions on the groups, ok. Thanks i hope they come out soon. Because I think this plugin has potential.  I hope i didn't cause any problems with asking these questions. I just figured something that might be a solution or change something would be good to know. I'm very happy to hear about prison 2.2

**Comment by Badcholo** [comment]
So i am using version Prison v2.0.6 but as i keep doing /rankup i keep getting ranked up to the second rank only. I can't seem to rankup the inheritance list. I am Using Kcauldron 1492.155
I'll look into replacing vault and or updating it if possible. Vault version: 1.5.2-b33

**Comment by SirFaizdat** [comment]
@Badcholo Why not use v2.1.6?

**Comment by Badcholo** [comment]
oh i thought it was only for 1.8 and up

**Comment by SirFaizdat** [comment]
@Badcholo Please make your own issue for this :)

**Comment by Badcholo** [comment]
I tried v2.1.6 I still get ranked up to only the second one. I figured it was the same issue, but will do.
