### ISSUE TITLE
Mine Reset Question

### ISSUE THREAD

**Issue by Minecrafterxbox** [SirFaizdat/Prison#108]
Hello, I really like this plugin, but I would like to set it so the mines reset after a certain percentage is broken. I don't think it is a command but I don't know for sure. Thank you for your time!

**Comment by SirFaizdat** [comment]
It is not, but it will be in version 3.0. However, there is a plugin that can do this, though it's paid. I'll send the link if you would like :)

**Comment by Minecrafterxbox** [comment]
Sure.

**Comment by SirFaizdat** [comment]
https://www.spigotmc.org/resources/prisonmines.4046/
It's 7.99 GBP, but it's heavily going to inspire the (free) Prison 3.0 mines system.
