### ISSUE TITLE
Can't rank up past the second rank.

### ISSUE THREAD

**Issue by Badcholo** [SirFaizdat/Prison#109]
I setup all the ranks properly. The config file shows the ranks properly and in order.
I type in rankup and i get ranked up from default to the second rank called Rank2.
I type in rankup again and i keep getting ranked to Rank2. I enabled Multiworld and this does not help.
Is there maybe a permission i'm missing?

Edit, The mines work great and are so easy and simple to use and configure. Thanks.
There are the server logs incase you want to look into something.

https://www.dropbox.com/sh/zaoe7lbightlhk2/AACC6JGdmUkBrEU7y7DGBgsya?dl=0

**Comment by SirFaizdat** [comment]
Currently past midnight for me, will look into in the morning.

**Comment by Badcholo** [comment]
Did you need anything else?
https://www.dropbox.com/s/vr0m12cl3t9ez34/GroupManager.zip?dl=1

**Comment by SirFaizdat** [comment]
I am working on a patch that will fix GroupManager support. For now, I highly recommend switching to PermissionsEx. See if that works and tell me.

**Comment by Badcholo** [comment]
crud, i don't know how to use permissionex. I'd have to learn how to use that plugin from scratch.
I might look into a rankup plugin. I have setup the mines per entry set to a certain rank. so coal mine is for default and iron mine will be for Rank2. They will be able to access the mines when they pay X amount of in game money to rankup.

I am willing to make a test server with permissionex and see if that works.
I think the problem is that groupmanger was abandoned. very odd cause it's a really nice plugin.
I'll keep you updated on what the root cause is if i can find a compatibility problem with another plugin or vault.

**Comment by Badcholo** [comment]
how about using something like this? it's open source and the config is so easy to configure.
You would just have to change the commands to /rankup. hope this helps maybe. Maybe a special version for Groupmanager. 
https://bitbucket.org/krisdestruction/groupmanagerpromote/src
http://www.curse.com/bukkit-plugins/minecraft/groupmanagerpromote#c2
Simple as 
Default
    Default : Rank2
     Rank2 : Rank3
     Rank3 : Rank4

**Comment by Badcholo** [comment]
I used the command /manuadd Badcholo Default 
and it kept ranking me up the ranks from default to rank8 and you can add in as many ranks as you want.

**Comment by SirFaizdat** [comment]
I was going to do something similar in that you can optionally define the next rank. You'll see when v2.2 comes out :) Glad you found a solution.

**Comment by Badcholo** [comment]
I'm using now http://dev.bukkit.org/bukkit-plugins/promotionessentials/
It works really great and is very easy to configure.

Also i have just checked on my 3 mines and they are not loaded. I don't know why or when they got unloaded. I still see the mines in the configs folder, but they aren't active. I had set regions and global flags to setup with ranks so that players only have access to certain ranks until they rankup.
Very odd. I have save-all and restarted the server, but they aren't coming back up.

**Comment by Badcholo** [comment]
Is there a command to reload the mines from the config?

**Comment by SirFaizdat** [comment]
@Badcholo What do you mean ("Is there a command to reload the mines from the config?")?

**Comment by Badcholo** [comment]
sry for the late reply. Since my mines are not loading up and any attempt to load the mines has failed. I  can see the mines in the config, but they are just not loading. I would have to remake all the mines again after deleting for it to happen again. I was just checking to see if there was a command to force a load.
