### ISSUE TITLE
Everytime someone ranks up, they lose the previous ranks permissions. [Pex]

### ISSUE THREAD

**Issue by Blazer28** [SirFaizdat/Prison#110]
I've been using this prison plugin for a while now, and it works very well. The small but extremely important problem i've had, is that every time someone uses /rankup , there permissions are whiped clean (pex), and they only have the permissions of the new group. This affects my staff and donator ranks. Any solutions to the problem?
Thanks,
-Blazers_28

**Comment by DeagleGaming** [comment]
Your groups need to inherit the permissions of the previous rank. For example, B inherits the permissions of A, C inherits the permissions of B and so on. 

Hope this helps!

**Comment by Blazer28** [comment]
Ive seen people talk about ladders... Im not having problems with the A, B, C, etc, ranks, i just give them all the permissions needed, but donators and/or staff get there ranks taken away when they rankup.

**Comment by Badcholo** [comment]
A player can only be in 1 group or rank at a time. so if they rankup, obviously they will move into that rank/group with only the permissions set in that group/rank.

**Comment by Blazer28** [comment]
So how am i supposed to make donators and staff keep there ranks?

**Comment by SirFaizdat** [comment]
PermissionsEx actually supports more than one group per player. Create it as normal and type (using an Admin group as an example) either ```/pex groups Admin user add <username>``` or ```/pex user <username> group add Admin```. Both will work the same. Prison will only focus on the ones in the primary ladder, which are A-Z.

**Comment by Blazer28** [comment]
Ohh ok SirFaizdat. Do I have to create ladders myself?

**Comment by SirFaizdat** [comment]
No, create the groups as normal, but don't add them to Prison.

**Comment by Blazer28** [comment]
ohh ok

**Comment by Badcholo** [comment]
I see.

**Comment by SirFaizdat** [comment]
Did you get it working?

**Comment by Blazer28** [comment]
Yes I did thanks
