### ISSUE TITLE
Emergency Update Notification does not dissapear

### ISSUE THREAD

**Issue by VoltMC** [SirFaizdat/Prison#111]
I'd like to report that the notification for the Emergency Update for Prison 2 when you log in does not dissapear. Even though I do /prison update and says it was completed successfully, it keeps popping up.

**Comment by SirFaizdat** [comment]
Yes, I know (it’s been bothering me on my own server as well). It has to do with something screwed up with the Updater API. I’ll have to either write my own for the next update or fix the current one. Thanks for point this out :)

**Comment by SirFaizdat** [comment]
For now you can disable update checks in config.yml, but make sure you check the plugin page periodically for updates.

**Comment by SirFaizdat** [comment]
Closed as this is a Prison 2 bug report, and no more updates will be made to Prison 2.
