### ISSUE TITLE
Prison 2 not working with vip ranks

### ISSUE THREAD

**Issue by bcmmbc122333** [SirFaizdat/Prison#112]
When someone is a VIP rank and they rank up with prison 2, it ups the default rank and keeps the VIP suffix, and in the permission file its self it still has them listed in both groups, but the VIP commands won't work after a rank up. when I manually change there rank to the default block and VIP it works. I'm running PEX at the moment.

**Comment by SirFaizdat** [comment]
Can you send me your PermissionsEx files so that I can try to reproduce the issue?

**Comment by SirFaizdat** [comment]
Closed for inactivity (it's been 2 months). Reopen if the problem persists.
