### ISSUE TITLE
Prison Ranks

### ISSUE THREAD

**Issue by ilipily** [SirFaizdat/Prison#113]
Hello,
There is a problem when i make a rank it says: An internal error occured while attempting to perform this command. And what i typed was : /prisonranks add A 0 [A] . 

Can you help me ?

**Comment by SirFaizdat** [comment]
What's the error in the console?

**Comment by ilipily** [comment]
https://gyazo.com/5128bc17c9611fef048d34ceaff28a97

**Comment by SirFaizdat** [comment]
Will look into soon (very busy currently). By any chance, do you have an outdated version of PermissionsEx? Make sure you have the latest version of Vault and PermissionsEx.

**Comment by tyler58546** [comment]
I Had This Issue, Updating Pex Works.

**Comment by SirFaizdat** [comment]
Any update on the situation? Have you updated PermissionsEx?

**Comment by ilipily** [comment]
Yes, thank you.
