### ISSUE TITLE
'The rank doesn't exist'

### ISSUE THREAD

**Issue by Troller4Ever** [SirFaizdat/Prison#114]
If I do /prisonranks add A 0 [&2&lA&r] it says 'Prison > That rank doesn't exist'.
What do I have to do?

Console:
18.12 15:55:01 [Server] INFO Admins: [Owner]~Troller
18.12 15:54:27 [Server] INFO Admins: [Owner]~Troller
18.12 15:53:53 [Server] INFO Admins: [Owner]~Troller
18.12 15:53:19 [Server] INFO Admins: [Owner]~Troller
18.12 15:52:45 [Server] INFO Admins: [Owner]~Troller
18.12 15:52:29 [Server] INFO at java.lang.Thread.run(Thread.java:745)
18.12 15:52:29 [Server] INFO at me.codercloud.installer.util.BaseUtil$RunTask.run(BaseUtil.java:537)
18.12 15:52:29 [Server] INFO at me.codercloud.installer.util.Task.start(Task.java:24)
18.12 15:52:29 [Server] INFO at me.codercloud.installer.util.tasks.MenuTask.run(MenuTask.java:71)
18.12 15:52:29 [Server] INFO at me.codercloud.installer.search.InstallPluginFiles.run(InstallPluginFiles.java:187)
18.12 15:52:29 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
18.12 15:52:29 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
18.12 15:52:29 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
18.12 15:52:29 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:175)
18.12 15:52:29 [Server] INFO at ru.tehkode.permissions.PermissionManager.<init>(PermissionManager.java:64)
18.12 15:52:29 [Server] INFO java.lang.NullPointerException
18.12 15:52:29 [Server] ERROR Error occurred with PermissionsEx! Please post it to http://git.io/v0N6S. Full error:
18.12 15:52:29 [Multicraft] Skipped 2 lines due to rate limit (30/s)
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_60]
18.12 15:52:28 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_60]
18.12 15:52:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_60]
18.12 15:52:28 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
18.12 15:52:28 [Server] INFO at com.earth2me.essentials.EssentialsPluginListener.onPluginDisable(EssentialsPluginListener.java:48) ~[?:?]
18.12 15:52:28 [Server] INFO at com.earth2me.essentials.perm.PermissionsHandler.checkPermissions(PermissionsHandler.java:121) ~[?:?]
18.12 15:52:28 [Server] INFO at com.earth2me.essentials.perm.PermissionsExHandler.<init>(PermissionsExHandler.java:17) ~[?:?]
18.12 15:52:28 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.getPermissionManager(PermissionsEx.java:405) ~[?:?]
18.12 15:52:28 [Server] INFO Caused by: ru.tehkode.permissions.exceptions.PermissionsNotAvailable: Permissions manager is not accessable. Is the PermissionsEx plugin enabled?
18.12 15:52:28 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
18.12 15:52:28 [Server] INFO at me.codercloud.installer.util.BaseUtil$RunTask.run(BaseUtil.java:537) [Installer.jar:?]
18.12 15:52:28 [Server] INFO at me.codercloud.installer.util.Task.start(Task.java:24) [Installer.jar:?]
18.12 15:52:28 [Server] INFO at me.codercloud.installer.util.tasks.MenuTask.run(MenuTask.java:71) [Installer.jar:?]
18.12 15:52:28 [Server] INFO at me.codercloud.installer.search.InstallPluginFiles.run(InstallPluginFiles.java:187) [Installer.jar:?]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at ru.tehkode.permissions.bukkit.PermissionsEx.onEnable(PermissionsEx.java:282) [PermissionsEx.jar:?]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:358) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-BT45_1.8.8_10.21.jar:git-Spigot-5f38d38-18fbb24]
18.12 15:52:28 [Server] INFO org.bukkit.event.EventException
18.12 15:52:28 [Server] ERROR Could not pass event PluginDisableEvent to Essentials vTeamCity
18.12 15:52:28 [Server] INFO Essentials: Using PermissionsEx based permissions.
18.12 15:52:28 [Server] INFO WEPIF: GroupManager detected! Using GroupManager for permissions.
18.12 15:52:28 [Server] INFO Disabling PermissionsEx v1.23.3
18.12 15:52:28 [Server] INFO Enabling PermissionsEx v1.23.3
18.12 15:52:22 [Server] INFO Found a bug? Report it at our website: http://foreverpumpkin.enjin.com/.
18.12 15:52:11 [Server] INFO Admins: [Owner]~Troller
18.12 15:51:36 [Server] INFO Admins: [Owner]~Troller
18.12 15:51:02 [Server] INFO Admins: [Owner]~Troller
18.12 15:50:28 [Server] INFO Admins: [Owner]~Troller
18.12 15:50:21 [Server] INFO Check out our website! http://foreverpumpkin.enjin.com/.
18.12 15:49:54 [Server] INFO Admins: [Owner]~Troller
18.12 15:49:20 [Server] INFO Admins: [Owner]~Troller
18.12 15:48:46 [Server] INFO Admins: [Owner]~Troller
18.12 15:48:20 [Server] INFO Stuck? The server is still in progress, try to use /spawn.
18.12 15:48:12 [Server] INFO Admins: [Owner]~Troller
18.12 15:48:05 [Server] INFO Mines have been reset!
18.12 15:48:05 [Server] INFO Saved the world
18.12 15:48:05 [Server] INFO Saving...
18.12 15:48:05 [Server] INFO Saving is already turned on.
18.12 15:48:05 [Multicraft] Auto-saving world...
18.12 15:47:38 [Server] INFO Admins: [Owner]~Troller
18.12 15:47:03 [Server] INFO Admins: [Owner]~Troller
18.12 15:46:47 [Server] INFO Disabling CustomHelp v0.3
18.12 15:46:29 [Server] INFO Admins: [Owner]~Troller
18.12 15:46:19 [Server] INFO Our WebManager's YouTube https://www.youtube.com/channel/UCIg86MKUSM5AS43AOkPfyWg
18.12 15:45:55 [Server] INFO Admins: [Owner]~Troller
18.12 15:45:47 [Server] INFO Napkin0fDestiny left the game.
18.12 15:45:47 [Disconnect] User Napkin0fDestiny has disconnected, reason: Disconnected
18.12 15:45:21 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:45:21 [Server] INFO Admins: [Owner]~Troller
18.12 15:44:47 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:44:47 [Server] INFO Admins: [Owner]~Troller
18.12 15:44:18 [Server] INFO Check out the co-owner's youtube! https://www.youtube.com/channel/UCwBblu19aB8kBfx7Lfrj51A
18.12 15:44:13 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:44:13 [Server] INFO Admins: [Owner]~Troller
18.12 15:43:39 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:43:39 [Server] INFO Admins: [Owner]~Troller
18.12 15:43:05 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:43:05 [Server] INFO Admins: [Owner]~Troller
18.12 15:42:30 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:42:30 [Server] INFO Admins: [Owner]~Troller
18.12 15:42:17 [Server] INFO Do not panic!  This Server is currently in BETA Mode!
18.12 15:41:56 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:41:56 [Server] INFO Admins: [Owner]~Troller
18.12 15:41:22 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:41:22 [Server] INFO Admins: [Owner]~Troller
18.12 15:40:53 [Server] INFO [Troller4Ever: Set game difficulty to Peaceful]
18.12 15:40:48 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:40:48 [Server] INFO Admins: [Owner]~Troller
18.12 15:40:16 [Server] INFO Need Help From A Staff Member? Just Do /Staff Or /List!
18.12 15:40:14 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:40:14 [Server] INFO Admins: [Owner]~Troller
18.12 15:39:40 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:39:40 [Server] INFO Admins: [Owner]~Troller
18.12 15:39:06 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:39:06 [Server] INFO Admins: [Owner]~Troller
18.12 15:38:32 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:38:32 [Server] INFO Admins: [Owner]~Troller
18.12 15:38:13 [Server] INFO Found a bug? Report it at our website: http://foreverpumpkin.enjin.com/.
18.12 15:38:03 [Server] INFO Mines have been reset!
18.12 15:38:01 [Server] INFO Saved the world
18.12 15:38:01 [Server] INFO Saving...
18.12 15:38:01 [Server] INFO Saving is already turned on.
18.12 15:38:01 [Multicraft] Auto-saving world...
18.12 15:37:57 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:37:57 [Server] INFO Admins: [Owner]~Troller
18.12 15:37:23 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:37:23 [Server] INFO Admins: [Owner]~Troller
18.12 15:36:49 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:36:49 [Server] INFO Admins: [Owner]~Troller
18.12 15:36:24 [Server] INFO bryan34789 left the game.
18.12 15:36:24 [Disconnect] User bryan34789 has disconnected, reason: Disconnected
18.12 15:36:15 [Server] INFO Moderator: [Moderator]Napkin0fDestiny
18.12 15:36:15 [Server] INFO Default: [Member]bryan34789
18.12 15:36:15 [Server] INFO Admins: [Owner]~Troller

**Comment by SirFaizdat** [comment]
You appear to be having an error with PermissionsEx, and that may be why it is not working.

**Comment by SirFaizdat** [comment]
Make sure all of these things are up to date:

* Vault
* PermissionsEx
* Prison

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by SirFaizdat** [comment]
I'm going to close the ticket for inactivity over 2 weeks. If the problem persists, just reopen
