### ISSUE TITLE
Mines in the end???!!!

### ISSUE THREAD

**Issue by Teomania** [SirFaizdat/Prison#115]
if i make a mine in the overworld and do /mines reset "nameofmine"
they don't do anything... just as i got to the end, i saw they where spawning there...
is there a fix for this becouse the last update seemed working, but this one doesn't

(also it says i need to update but after /prison update it updates (even checked plugins folder)
but it keeps asking...)

**Comment by SirFaizdat** [comment]
What happens if you create a new mine in the over world? Does it still spawn in the end?

Also, the update message is something to do with the Updater code. You can disable update checks in config.yml, but be sure to check the plugin page periodically for updates.

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by SirFaizdat** [comment]
Closed for inactivity (it's been 2 months). Reopen if the problem persists.
