### ISSUE TITLE
/Rankup is bugged?

### ISSUE THREAD

**Issue by Revolurion** [SirFaizdat/Prison#116]
Hey, i have an issue I have made all the prisonranks, and they are all in /ranks but when i rankup from c to d it ranks me up from c to c 
Link https://gyazo.com/90c4fb0f79920929656d06cacec0c79c
And i'm not getting an error in the console.
And i have the last emergency update installed.

Regards, Jordy

**Comment by SirFaizdat** [comment]
Are you using GroupManager? If so, I recommend you switch to PermissionsEx. GroupManager isn't very compatible because it's so outdated.

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by SirFaizdat** [comment]
Closed for inactivity (it's been 2 months). Reopen if the problem persists.
