### ISSUE TITLE
Mines Setspawn Bug

### ISSUE THREAD

**Issue by ThePokeGod** [SirFaizdat/Prison#117]
I use the /mines setspawn (letter) command on my mines, but players aren't teleported to that location when the mines reset.

**Comment by prizmonyx** [comment]
ya the same thing happens for me man i hope this gets fixed soon

**Comment by SirFaizdat** [comment]
This feature is broken. I'm working on a fix for this and many other features as well, which is why it's taking so long. I don't have an ETA as of now.

**Comment by SirFaizdat** [comment]
Closed as this is a Prison 2 report, and no more updates will be made to Prison 2.
