### ISSUE TITLE
Moves me back to group A when i rankup twice.

### ISSUE THREAD

**Issue by kasper227232** [SirFaizdat/Prison#118]
Hello.

I a bunch of groups from A - Z. When im in rank A and then rankup to B it works fine, but when i rankup from B to C it moves me back to A then when i rankup again it moves me to D. I use GroupManager for this.

I have a picture here.
![2015-12-28_14 33 24](https://cloud.githubusercontent.com/assets/16445511/12019407/2a9319d8-ad70-11e5-8422-f84e24a25942.png)

**Comment by SirFaizdat** [comment]
Is there a way you can switch to PermissionsEx? GroupManager does not work too well with the rankup system.

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by SirFaizdat** [comment]
Closed for inactivity (it's been 2 months). Reopen if the problem persists.
