### ISSUE TITLE
PermissionEx temp rank website

### ISSUE THREAD

**Issue by Makros25** [SirFaizdat/Prison#119]
hi all , i made ranks in my server with permissionEx and it works fine but i wanted a timed rank (/pex user <username> group add vip "" 604800) from the website Cmw it works on server but website no
i just cant find the right command for it i did this one   (pex user pseudo_var group add vip "" 604800;)
dosn't work i'am working with jsonapi

**Comment by Camouflage100** [comment]
In the command, `pex user pseudo_var group add vip "" 604800`, the "" might be messing it up.

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by SirFaizdat** [comment]
Closed for inactivity (it's been over 2 months), reopen if the problem persists.
