### ISSUE TITLE
NPE for v2.1.6 EmergencyPatch

### ISSUE THREAD

**Issue by astr1al** [SirFaizdat/Prison#120]
Not sure what the cause it but after a few hours of uptime my console will start randomly spitting out this error.

http://pastebin.com/Tj4q1uPd

This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)[m

If it matters, I am running BosEconomy6

**Comment by SirFaizdat** [comment]
Looks like the plugin is having trouble finding the balance of a player. Does BE6 have that player registered?

**Comment by SirFaizdat** [comment]
May I have your Prison folder (in a zip file) so that I can attempt to recreate the situation?

**Comment by astr1al** [comment]
https://dl.dropboxusercontent.com/u/87013016/Prison.rar

Sorry for the late response, I am unable to reproduce this error, it just seems to happen out of no where if the server has a lag spike maybe?

**Comment by SirFaizdat** [comment]
It's working now?

**Comment by astr1al** [comment]
haven't seen the error in a while. i think it may be from another plugin
lagging up the server and messing with other plugins.

**Comment by SirFaizdat** [comment]
Going to close this then. Usually I'd investigate this error further but with Prison 3 right around the corner, further investigation isn't necessary.
