### ISSUE TITLE
RANK Bugg

### ISSUE THREAD

**Issue by Prison2Bugg** [SirFaizdat/Prison#121]
![2016-01-03_18 18 44](https://cloud.githubusercontent.com/assets/16527992/12079795/acadadf4-b246-11e5-8086-d284bffc07ff.png)
Thats The Bugg Please Help me
![2016-01-03](https://cloud.githubusercontent.com/assets/16527992/12079800/d7f08b9e-b246-11e5-966b-e982380135e6.png)
And Ranks
![2016-01-03 1](https://cloud.githubusercontent.com/assets/16527992/12079809/1440a49e-b247-11e5-9814-6b5086360653.png)

**Comment by Prison2Bugg** [comment]
Its With The First Rank that i Create

**Comment by SirFaizdat** [comment]
GroupManager is no longer supported by Prison because it is outdated and therefore does not work properly with the new system. I recommend you switch to PermissionsEx.

**Comment by Prison2Bugg** [comment]
How to Work PremissionsEx? xD
