### ISSUE TITLE
/prisonranks add rank (propper rank info) not working

### ISSUE THREAD

**Issue by Th3FunkyChick3n** [SirFaizdat/Prison#124]
When I do the command all I get is this message http://prntscr.com/9ohahz . Any troubleshooting ideas? Here are my installed plugins for reference http://prntscr.com/9ohb2q. It could be likely there is interferece but where, I wouldn't know.

**Comment by SirFaizdat** [comment]
Are you sure the rank you are trying to add is the same name as the one you have set up in GroupManager?

**Comment by Th3FunkyChick3n** [comment]
I added the groups in groupmanager and still received the same message

**Comment by Th3FunkyChick3n** [comment]
nevermind that. it's working. Thanks for the help!
