### ISSUE TITLE
Mines not resetting.

### ISSUE THREAD

**Issue by Ranger1x** [SirFaizdat/Prison#125]
Hello guys, the mines that I have created on my server are not resetting it all.  Any help would be nice.

**Comment by jakeob28** [comment]
Please help.
I am having the same problem.

**Comment by SirFaizdat** [comment]
Is there any error in the console?

**Comment by jakeob28** [comment]
Found the issue! (And I believe it might be Ranger's problem too). I forgot to addblock to the mines, so it did not know what blocks to fill.

**Comment by jakeob28** [comment]
Found the issue! (And I believe it might be Ranger's problem too). I forgot to addblock to the mines, so it did not know what blocks to fill.

**Comment by SirFaizdat** [comment]
@jakeob28 Great!
@Ranger1x Does adding blocks to the mine using /mines addblock fix the issue?

**Comment by Ranger1x** [comment]
Yes it does, thanks!
