### ISSUE TITLE
There was an error in starting ranks. Check console for details.

### ISSUE THREAD

**Issue by EkqoTheGecko** [SirFaizdat/Prison#127]
Whenever i try to add a rank i get this error message. ^^^
https://gyazo.com/f11bb4143cd4523c0e447f406008a3f0

**Comment by SirFaizdat** [comment]
Looks to me like something is wrong with PermissionsEx.

**Comment by EkqoTheGecko** [comment]
Do you have any idea what it could be?

**Comment by SirFaizdat** [comment]
Try updating both Vault and PermissionsEx.
