### ISSUE TITLE
/rankup problem

### ISSUE THREAD

**Issue by Th3FunkyChick3n** [SirFaizdat/Prison#128]
I have the ranks (and their inheritances) set up correctly (in permissionsex) and I added the ranks into the Prison plugin yet it will just repeatedly rank me up (and charge me) for rank a even though b and the inheritance between the two are already there. any ideas?

**Comment by SirFaizdat** [comment]
Could you send me your Prison and PermissionsEx files?

**Comment by Th3FunkyChick3n** [comment]
[Prison.zip](https://github.com/SirFaizdat/Prison/files/111082/Prison.zip)
[PermissionsEx.zip](https://github.com/SirFaizdat/Prison/files/111084/PermissionsEx.zip)

**Comment by SirFaizdat** [comment]
Try setting their positions in the rank ladder. A should be 1, B should be 2, and so on.
