### ISSUE TITLE
Ran does not exist (Plz help)

### ISSUE THREAD

**Issue by TMMCraftOwner** [SirFaizdat/Prison#129]
I do the command /Pranks add a 0 &8[&6A&8] 
And it replies with "This rank does not exist" plz help i use bPermissions not Pex and have the latest version of Prison if you could either plz help me fix this or tell me a small tutorial how to code em in config that would be great plz

**Comment by SirFaizdat** [comment]
Is there an error message in the console?
Are you creating the rank in bPermissions first (case sensitive)?

**Comment by TMMCraftOwner** [comment]
There is no error code in the console and i do not sue bperms to create ranks (for the prison ranks) as i do not know how

**Comment by SirFaizdat** [comment]
Prison 2's rank system basically uses your groups plugin and ranks you up through the setup groups. You need to have a group called "a" in bPermissions.

Prison 3 will change this.

**Comment by TMMCraftOwner** [comment]
ok when will prison 3 be released i can't wait

**Comment by SirFaizdat** [comment]
It will be released on February 14th, 2016.

http://springpoint.xyz/prison/
