### ISSUE TITLE
How to not let a rank mine in b rank

### ISSUE THREAD

**Issue by kingdeathmore** [SirFaizdat/Prison#130]
So I have world gaurd world edit vault etc. and of course I made my regions with world gaurd but realized players cant break the mines, so then I allowed passthrough and they could break everything but heres the real problem, I went on my alt and I was able to mine the B mine as a A rank!

This really isnt a bug or anything but I really need some help! I use PermissionsEx

**Comment by kingdeathmore** [comment]
Anyone?

**Comment by SirFaizdat** [comment]
There's a good guide here. https://bukkit.org/threads/how-to-use-the-entry-group-flag-in-worldguard.124066/
