### ISSUE TITLE
You're too rich to rank up!

### ISSUE THREAD

**Issue by FloThePony** [SirFaizdat/Prison#131]
https://gyazo.com/7862fb95a4ea1899cb060dd51aa900a1

Rest in peace.

I have $900, but by the looks of it, I'm too rich for a $400 rank...

**Comment by SirFaizdat** [comment]
What economy plugin do you use,

**Comment by FloThePony** [comment]
Vault and [BottomLine](https://www.spigotmc.org/resources/bottomline-the-new-alternative-to-essentials.15348/).

**Comment by SirFaizdat** [comment]
I'm going to assume that it's a bug with BottomLine or its integration with Vault, because Prison merely asks Vault for the balance.

**Comment by FloThePony** [comment]
Ah, thanks.
