### ISSUE TITLE
Can I Use GroupManager To Link Ranks

### ISSUE THREAD

**Issue by nicktrick92** [SirFaizdat/Prison#133]
Hello!

So I create a Groupmanager Rank 'A' and I create a prisonRank 'A', and it looks like they link (The prionrank A cannot be created until I create the groupmanager one, then it works). However, when I rankup, it doesn't change my groupmanager rank... I know it said GroupManager is not supported anymore, but is there any way we can still hook our Gm ranks and prisonranks together? All of our current ranks are on GroupManager and it would be tough to switch everything over to PEX!

Thanks,

-Nick

I am using release 2.1.5 if it matters

**Comment by nicktrick92** [comment]
Okay, so we decided to switch to PEX as I learned that it would not be as difficult as I had expected... I hope the plugin works with PEX!

Thanks,

-Nick

**Comment by SirFaizdat** [comment]
The plugin works with PermissionsEx very well. Hope it works out!

**Comment by nicktrick92** [comment]
Another question... Is there some type of HUD plugin that hooks into prison and allows for players to visually see their stats?

**Comment by SirFaizdat** [comment]
I don't know of any HUD plugins that integrate with Prison, unfortunately.

You ensure that the group B inherits the group A in PermissionsEx, and then type /rankup.
