### ISSUE TITLE
Ranks not loading on start

### ISSUE THREAD

**Issue by MihaMi27** [SirFaizdat/Prison#136]
I made everything as the guide says, but as long as I don't reload or close my server ranks work, if I do close it, when I come back on, I need to add all ranks again. Console doesn't report anything.

**Comment by SirFaizdat** [comment]
Could you send me your Prison folder in a zip file so that I may attempt to reproduce the problem?

**Comment by MihaMi27** [comment]
Yes, give me 10 minutes just to upload it.

**Comment by MihaMi27** [comment]
I cannot upload it, because its too big, for permissions I only use op or non-op.

https://drive.google.com/file/d/0B_Ll8ct3ULX8SnRwV240ZXJCUUk/view

**Comment by SirFaizdat** [comment]
I can't access the file.

**Comment by MihaMi27** [comment]
Now?

https://drive.google.com/file/d/0B_Ll8ct3ULX8SnRwV240ZXJCUUk/view?usp=sharing

**Comment by SirFaizdat** [comment]
Still unable to open the file. (Sorry for the late reply)

**Comment by MihaMi27** [comment]
Okay :)

**Comment by SirFaizdat** [comment]
Wow, I can't believe I kept you waiting for two months! My sincerest apologies :(

**Comment by MihaMi27** [comment]
Well, I thought that you are probably busy doing important stuff :P

**Comment by SirFaizdat** [comment]
I have to write some tools to be able to debug this issue, so sorry if it takes too long :(

**Comment by MihaMi27** [comment]
No problem, I won't be using any servers until the end of June :)

**Comment by SirFaizdat** [comment]
The issue was right under our noses. It turns out that the ranksList.txt file has been edited. This is not the file to be edited - it is an index file so Prison knows what ranks to look for. This file is handled by Prison automatically.

Here's your new file: [ranksList.txt](https://github.com/SirFaizdat/Prison/files/260214/ranksList.txt)
