### ISSUE TITLE
Rankup "no permission"

### ISSUE THREAD

**Issue by Mihaion** [SirFaizdat/Prison#138]
Hi! 

Everything works perfekt for me but my Group/player can´t use /rankup. "no permission" But there is not listet one permision node on that. If i give them prison.rankup it don't work but works when i give them prison.* but them gives them to many permissions or ?

Use bungeeperms for permissions. 

Regards

**Comment by SirFaizdat** [comment]
Try the permission prison.ranks.purchase.

**Comment by Mihaion** [comment]
Thank you SirFaizdat! :)

Have a nice day.

regards

2016-04-04 13:05 GMT+02:00 SirFaizdat <notifications@github.com>:
