### ISSUE TITLE
Rankup Glitch

### ISSUE THREAD

**Issue by AsrielDreeemurr** [SirFaizdat/Prison#142]
Howdy! So I know people have had this glitch before. When I type /rankup, it just ranks me up to the same rank as previous. I have all the inheritance right and all of the ladder setup. Help! What should I do?!

Also the files don't want to upload :/

**Comment by SirFaizdat** [comment]
Did you try uploading them to [Pastebin](http://pastebin.com)? I need the files to help.

**Comment by AsrielDreeemurr** [comment]
I can't find out how to upload them to it. Is there something else I could use, like google drive since I know how to do that?

**Comment by SirFaizdat** [comment]
Sure, as long as I can access it ;)

**Comment by AsrielDreeemurr** [comment]
https://drive.google.com/folderview?id=0B13sNIljjM2hMTl1Wnd6WWhDNm8&usp=sharing

This SHOULD work.

**Comment by SirFaizdat** [comment]
It appears to have worked, I'll look into it when I get on a computer.

**Comment by AsrielDreeemurr** [comment]
Okay, thank you!

**Comment by AsrielDreeemurr** [comment]
AHH! I found out the issue! I wasn't using just letters for the names, it was based off of something else. I fixed it, thanks anyway for trying! lol
