### ISSUE TITLE
I have a problem with ranks

### ISSUE THREAD

**Issue by dino147** [SirFaizdat/Prison#144]
After rank J (1 billon $) when a player types /rankup he gets demoted to the lowest rank,not promoted to rank K (10 billon $ ) could you solve this please ?

**Comment by SirFaizdat** [comment]
Does K inherit J?

**Comment by dino147** [comment]
Yes, /pex group K create J ,this is the command,...and i think that inherits

**Comment by SirFaizdat** [comment]
Are they both on the same ladder?

**Comment by SirFaizdat** [comment]
Is there any update on the situation? Are groups K and J on the same rank ladder?

**Comment by dino147** [comment]
You can close this ticket, the problem is solved. 
Thanks.
