### ISSUE TITLE
Rank glitches

### ISSUE THREAD

**Issue by ExoticPlayz10** [SirFaizdat/Prison#146]
Everytime i rankup from B to C it moves me to group A in the world and says u have been ranked up to C
HELP!

**Comment by SirFaizdat** [comment]
First, ensure that you are using something other than GroupManager, because GroupManager no longer works properly with Vault and therefore Prison. Next, ensure that each rank inherits the last rank, and is in the same rank ladder.

**Comment by ExoticPlayz10** [comment]
What can i use for example?

**Comment by SirFaizdat** [comment]
For PermissionsEx, each rank should be created like so:

`/pex group A create`
`/pex group B create A`
`/pex group C create B`
`/pex group Free create C`

and so on.
