### ISSUE TITLE
Prison mines limit working

### ISSUE THREAD

**Issue by camlam999** [SirFaizdat/Prison#147]
I've been using this plugin for a while for a-z mines as well as other mines for donors and such, but recently its come to my attention that once reaching Q mine that mines a-g had stopped working, they wouldn't reset and couldn't be edited because no mine exist with that name but when attempting to create a mine with the same it will say a mine already has that name, i went to the config files and dragged in some a backup from a couple days ago to see if that would fix it, and even then a few mines would not work correctly, I've tried doing this over and over and every time it seems a different mine is affected, ive always had errors with your rankup system of this plugin and got another one which works, the problem with this one is that it would go player "player has ranked up to B" and then B "player has ranked up to C" and then A and  a never ending repeat of that. Im using spigot 1.8.8 and using groupmanager if that helps at all

**Comment by SirFaizdat** [comment]
Can you please send me your Prison folder (`/plugins/Prison`)? This often has to do with a corrupted file.

**Comment by camlam999** [comment]
I've re-created ALL the mines and they seem to be working fine now, thanks
anyways but i know im not the only one with this problem

**Comment by SirFaizdat** [comment]
File corruption is the main cause of most Prison issues, I'm sorry that this happened!
