### ISSUE TITLE
Prisonranks add

### ISSUE THREAD

**Issue by MeneerPlatvis** [SirFaizdat/Prison#149]
I cant add ranks. When i use the right command it says that it had a internal error.

What can I do?

**Comment by SirFaizdat** [comment]
I need more information. Which command? Is there an error in console? If so, can you post it?

**Comment by MeneerPlatvis** [comment]
I don't know what happened, but the issue has solved by itself or something like that:)

**Comment by SirFaizdat** [comment]
:)
