### ISSUE TITLE
Rankup Prefixes

### ISSUE THREAD

**Issue by cubcreate** [SirFaizdat/Prison#150]
I have my prefixes set in PermissionsEx, but whenever I use the prison rankup system then their tag goes back to A2 or something else. ex: Before rankup [Helper] Namey : Hi! | After rankup [A1] Namey : Hi!

**Comment by SirFaizdat** [comment]
PermissionsEx doesn't allow for more than one prefix on a player. You can solve this by having the staff prefixes as suffixes, and the Prison rank prefixes as prefixes. It also helps to have the staff ranks in a separate ladder, so Prison doesn't confuse them with the prison ranks.

**Comment by cubcreate** [comment]
Thanks :+1:  It works :)
