### ISSUE TITLE
Rank does not exist!

### ISSUE THREAD

**Issue by PrisonTech** [SirFaizdat/Prison#153]
Basically I can't create a rank for god knows why

**Comment by SirFaizdat** [comment]
You need to add the rank in your permissions plugin first.

**Comment by PrisonTech** [comment]
how do I do that? Can you show me an example please?

**Comment by SirFaizdat** [comment]
`/pex group A create`

`/pex group B create A`

`/pex group C create B`

`/pex group D create C`

`/pex group E create D`

and so on.
