### ISSUE TITLE
Still not working

### ISSUE THREAD

**Issue by PrisonTech** [SirFaizdat/Prison#154]
I added the code you sent to the "Rankslist.txt" saved it then restarted the server and got on and there were still no ranks. was that not where I was supposed to put it? I have PermissionsEx but I dont know how to use it

**Comment by SirFaizdat** [comment]
Your files are corrupted, you must re-create your ranks. Delete the `ranks` folder and re-add your ranks using `/prisonranks add <group> <price> [coloredName]`
