### ISSUE TITLE
/pranks add not work

### ISSUE THREAD

**Issue by Hakuati** [SirFaizdat/Prison#155]
Hello, I have a problem with the command / pranks add ... If I use the command / pranks add A 10000 comes as a fault with the message : The Price value is invalid ?

Can you tell why I always get that, I know myself no more rat them with .

Mfg

**Comment by SirFaizdat** [comment]
Fixed in Prison v2.2.2, which you can download from [here](https://www.spigotmc.org/resources/prison.1223/update?update=98950).
