### ISSUE TITLE
Ranks are disabled

### ISSUE THREAD

**Issue by MrHumanTarget** [SirFaizdat/Prison#156]
I keep doing /pranks add A 0 and I keep getting "Ranks are disabled" in red text, but they aren't. Im in a world called mines, the config says ranks: true I'm just very confused on how to set this all up. I made a GroupManager rank called A too.

**Comment by SirFaizdat** [comment]
Check the console for error messages.

**Comment by MrHumanTarget** [comment]
[Prison] There was an error handling prisonranks. Reason: Permissions manager is not accessable. Is the PermissionsEx plugin enabled? Thats the only error I see. I dont use PEX, I use GroupManager

**Comment by SirFaizdat** [comment]
What happens when you type /vault-info? Can you send me the output?

**Comment by MrHumanTarget** [comment]
http://i.imgur.com/ly4RI7C.png

**Comment by SirFaizdat** [comment]
It appears you have PermissionsEx and GroupManager installed at the same time. You must pick one.

**Comment by MrHumanTarget** [comment]
Ok, I still had the PEX jar in my folder. By chance do you happen to have an already complete ranks list I can download somewhere?

**Comment by Camouflage100** [comment]
Pre-made rank files are not provided, that's something that you'll have to do on your own as a server owner/operator.

**Comment by MrHumanTarget** [comment]
But someone could be nice and give me one :D Im still stuck on this stupid Member rank now. Ranks B, D, F all say Member instead of their letter.

**Comment by Camouflage100** [comment]
Are the prefixes set correctly for the ranks?

**Comment by MrHumanTarget** [comment]
They are set both using /mangaddv B prefix [B] and /pranks set B prefix [B]

**Comment by Camouflage100** [comment]
Have you tried using PermissionsEx? It's better compatible with Prison. I recommend PermissionsEx over GroupManager anyways personally.

**Comment by MrHumanTarget** [comment]
I have no idea how to use Pex, whenever i tried to use it, I can never do anything. I'll OP myself and I still cant do anything and it's a pain.

**Comment by Camouflage100** [comment]
To add all permisisons: /pex user {your username} add *
To add a group: /pex user {your username} group add {group name}

**Comment by SirFaizdat** [comment]
Run this command in the console:

/pex user <yourUsername> add permissions.*

**Comment by MrHumanTarget** [comment]
I'll try this and get back to you.

**Comment by MrHumanTarget** [comment]
I'll be honest, I have no clue how to run Pex, I don't know how to set anything up.
Add /pex user add permissions.* and /pex MrHumanTarget add permissions.* gives and Error in command syntax.

**Comment by SirFaizdat** [comment]
’pex user MrHumanTarget add

**Comment by SirFaizdat** [comment]
`/pex user MrHumanTarget add permissions.*`

**Comment by Camouflage100** [comment]
I'm assuming this is no longer an issue?
