### ISSUE TITLE
Updater notification

### ISSUE THREAD

**Issue by Camouflage100** [SirFaizdat/Prison#158]
The updater notification displays the "Version 2.2.1" needs to be updated from "Version 2.2.2". 

![capture](https://cloud.githubusercontent.com/assets/11241823/16180621/d01d397a-364f-11e6-93ba-2a5906c7300a.PNG)

**Comment by SirFaizdat** [comment]
Once Bukkit's API is refreshed, that message should go away. This could take up to 36 hours.

**Comment by Camouflage100** [comment]
Alright

**Comment by Camouflage100** [comment]
Update on issue:
Version was officially released on 6/19/2016 at 2PM Central Standard Time (-06:00).
