### ISSUE TITLE
Hey! Nice plugin its super cool and easy to setup but we had 2 issues when were in the prison world we cant talk but in other worlds we can and like if we stand still for 10 seconds if were not opped we get kicked for afk even know we set the afk time limit to like 3 billion seconds lol...

### ISSUE THREAD

**Issue by TimeyKappa** [SirFaizdat/Prison#159]
Its a cool plugin and here is the plugins we have on the server we have
essentials prison 2.2.1 (ur plugin) UltimateHub CompassNavigation CS-CoreLib GroupManager HubEssentials Multiverese-Core Warp-Portals ProtocolLib QuickMarket QuickSell UltraCosmetics WorldEdit And WorldGuard Vault PingAPI

**Comment by SirFaizdat** [comment]
Do these problems still happen when Prison is disabled?

**Comment by Camouflage100** [comment]
@TimeyKappa Any updates on the issue?
