### ISSUE TITLE
Per-world Broadcasting Error

### ISSUE THREAD

**Issue by TimeyKappa** [SirFaizdat/Prison#160]
20.06 05:21:43 [Server] WARN handleDisconnection() called twice
20.06 05:21:43 [Disconnect] User GamingCreeper108 has disconnected, reason: §cKicked for being afk!
20.06 05:21:43 [Server] INFO HOPE YOUR ENJOYING
20.06 05:21:43 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
20.06 05:21:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot188.jar:git-Spigot-e4d4710-e1ebe52]
20.06 05:21:43 [Server] INFO at me.sirfaizdat.prison.mines.MinesManager$ResetClock.run(MinesManager.java:154) ~[?:?]
20.06 05:21:43 [Server] INFO at me.sirfaizdat.prison.mines.MinesManager.access$100(MinesManager.java:37) ~[?:?]
20.06 05:21:43 [Server] INFO at me.sirfaizdat.prison.mines.MinesManager.broadcastToWorld(MinesManager.java:66) ~[?:?]
20.06 05:21:43 [Server] INFO java.lang.NullPointerException
20.06 05:21:43 [Server] WARN Task #1529 for Prison v2.2.1 generated an exception
20.06 05:21:36 [Server] INFO §cGamingCreeper108 §4was denied access to command.
20.06 05:21:32 [Multicraft] GamingCreeper108 ran command Message of the Day

**Comment by SirFaizdat** [comment]
It seems like one of the worlds in your multiword list (in config.yml) does not exist. Can you check to make sure that they are valid worlds (it is case sensitive)?

**Comment by SirFaizdat** [comment]
Any update on the situation?

**Comment by Camouflage100** [comment]
@TimeyKappa update?

**Comment by Camouflage100** [comment]
Closed for inactivity
