### ISSUE TITLE
Mines Multi-world Malfunctions

### ISSUE THREAD

**Issue by jparrack** [SirFaizdat/Prison#161]
Console:
Mine A was not reset because the world it was created in (mines) can not be found.

The map is there and I can mvtp to it easily. Just when i reset the mines, they apparently are not there?

It should be noted that I am running this in Craftbukkit for Minecraft 1.10

**Comment by ItsGJK** [comment]
I'm getting this same error. Reloading the plugin will fix it for some time, but it will break all over again. (I don't know how yet)

**Comment by Camouflage100** [comment]
As stated, this bug will be fixed in the 2.2.3 update D:

**Comment by meowsome** [comment]
I also have this problem. They reset fine after creation, but after a restart I get the error "Did not reset mine (mine name) because the world it is in could not be found." for each mine

**Comment by Robslayer** [comment]
is happening to me now too

**Comment by Robslayer** [comment]
I Have a fix, go into the config, and change multi-world from false, true, then list the world that ur mines are in under the world-list part, and u should be good to go

**Comment by Camouflage100** [comment]
What @Robslayer said
