### ISSUE TITLE
Can't create ranks because of Permissions

### ISSUE THREAD

**Issue by titanfabien44** [SirFaizdat/Prison#162]
I type /prisonranks add A 10000 but it doesn't let me add ranks, instead it returns "The rank must be loaded into PermissionsEx first", what do I do?

**Comment by titanfabien44** [comment]
I'm just testing it out in a random world I made to test for a lot of Bukkit Plugins in 1.9.4

**Comment by SirFaizdat** [comment]
Do exactly what it says. Prison's rank system currently links with the permissions plugin to move players up through the permission plugin's groups.

**Comment by titanfabien44** [comment]
But how do I load it into PEX?

**Comment by titanfabien44** [comment]
When I try to run the first command it says "Sorry, you don't have enough permissions"

**Comment by SirFaizdat** [comment]
Go into your console and type `/pex user [your username] add permissions.*`

**Comment by titanfabien44** [comment]
Thanks! now my ranks work and I can rankup

**Comment by titanfabien44** [comment]
Is there any way I can see which rank I have?

**Comment by SirFaizdat** [comment]
You can do `/pex user [username]` to see the ranks attached to a player. You can also do `/pex group [group] prefix [prefix]` to set the prefix for a rank which is shown in chat.

**Comment by titanfabien44** [comment]
Thanks
