### ISSUE TITLE
Prison v3.0

### ISSUE THREAD

**Issue by SirFaizdat** [SirFaizdat/Prison#164]
Prison v3.0 is under heavy development, so I thought I'd create a central place where updates can be posted, questions can be asked, and progress can be tracked.

Prison v3.0 will be completely modular and comes in separate jar files. If you only want to use, say, mines, you just drag in the `PrisonMines.jar` file, along with the `Prison.jar` file for your platform, and you got mines running! Additionally, Prison v3.0 will be a lot more functional, with in-depth documentation (video and text tutorials) to help get you started - a crucial feature that Prison 2 lacks.

- [x] Core
- [x] Cells
- [ ] Shops
- [x] Ranks
- [ ] Mines
- [x] Spigot implementation
- [ ] Sponge implementation
- [ ] User interfaces

**Disclaimer:** The items in the above checklist are checked if the feature is in its later stages. It does not necessarily mean that the feature is done.

**Comment by Camouflage100** [comment]
Yay!

**Comment by ItsGJK** [comment]
yey :D 

i guess i'll have to revamp my prison server -.- its already out

**Comment by Camouflage100** [comment]
@ItsGJK We'll be adding a a version translator from Prison 2 to Prison 3 in the core, so no need :3

**Comment by SirFaizdat** [comment]
@Camouflage100 The converter may not work, because the very architecture of
Prison v3.0 is entirely different (for example, ranks are standalone).

**Comment by Camouflage100** [comment]
@SirFaizdat yes, but we've not tested it yet, so we don't know for sure :8ball:

**Comment by SirFaizdat** [comment]
I'm marking cells as stable enough to be functional, although it still needs commands and GUIs.

**Comment by Camouflage100** [comment]
Ranks is complete other than the fact of the economy integration with the rankup command :+1:

**Comment by SirFaizdat** [comment]
Once again, just because something is checked off does not mean it is totally complete. It just means that the API behind it is relatively stable and the user experience is what's left to add or refine.

**Comment by Sotlol1** [comment]
Will v3 work good with groupmanager?

**Comment by SirFaizdat** [comment]
Prison v3.0 is going to have an in-house ranks system and so it will no longer depend on a permission plugin.

**Comment by Sotlol1** [comment]
That sounds awesome.

**Comment by SirFaizdat** [comment]
It is, so many less bugs :)

**Comment by Camouflage100** [comment]
@SirFaizdat @Sotlol1 Yeah, too many complaints with permission plugins ranks, so we're just doing it in-house now XD

**Comment by SirFaizdat** [comment]
# End of Week 2 of Development 

We have made substantial and *astounding* progress. It's been a mere two weeks since we began working on Prison v3.0, and we have:

* 117 GitHub commits
* 11,290 lines of code
* Basic ranks and cells modules
* Shops and mines modules underway

This is definitely a lot faster than either of us could have anticipated. We began the project expecting to be done by November, but now we feel that Prison v3.0 could be ready as early as late this month or August. That's definitely quite some progress. 

To be fair, we are coding up these modules while remembering that we're going to be coming back and adding features to them, and refining them until we feel they can do more than what a totally free and open-source plugin should do. We've changed our philosophy of Prison from a simple utility into a plugin that can be tasked with managing the entire server (or, just the parts you choose - it's very modular). 

## Guides

One of the biggest mistakes with Prison v2.0 is the lack of user documentation. For many people, it is challenging to figure out how to properly set up mines and ranks to run smoothly and as expected. The philosophy behind Prison v2.0 was that it should be so easy to use that documentation shouldn't need to be required. However, everyone has different amounts of experience and skill sets, and the need for documentation is absolutely necessary. 

Prison v3.0 will come with a full library of screencasts and textual documentation to help users set it up and make the most out of its powerful features. They will be available for free in English, and we will be looking for volunteers to translate them into other languages as well. The screencasts will be scripted and easy to follow, and the documentation will be curated and refined for maximum clarity.

From both of us in the MC-Prison Team, we can't wait for you to finally be able to use what we've been working on for the past few weeks.

**Comment by PapiSquad** [comment]
Been awhile since the last post. Any more recent updates on development?

**Comment by SirFaizdat** [comment]
Prison v2.3 is underway with changes that will make the current version more stable for users. That way, we don't have to rush the development of Prison v3.0.

**Comment by PapiSquad** [comment]
So then would I be able to use the current prison and it would be alright to transfer when the new release comes out? Also Prison 2 doesn't really have the cells or anything does it.

On Jul 28, 2016, at 8:14 PM, Faizaan <notifications@github.com<mailto:notifications@github.com>> wrote:


Prison v2.3 is underway with changes that will make the current version more stable for users. That way, we don't have to rush the development of Prison v3.0.

-

**Comment by SirFaizdat** [comment]
Development has resumed on Prison v3.0. The goal of Prison v3.0 is for it to be the best it can be, and so we are operating on Facebook's development mantra: move fast and break things. At this stage, we think it's possible to add a v2.x -> v3.x converter, but additional setup will need to be done to take advantage of new features. 

For example, in Prison v2.x the ranks system merely moves a player through a permissions plugin's groups, while in v3.x the ranks system is standalone. So, the converter would most likely create ranks for each registered group in the Prison v2.x save files, which would require users to add the additional data that was absent in v2.x.
