### ISSUE TITLE
Ranks are disabled

### ISSUE THREAD

**Issue by TheFrostyNation** [SirFaizdat/Prison#168]
The config shows that ranks are currently enabled, however when I type in /ranks or /prisonranks or anything that has to deal with the ranking system I get the message "Ranks are disabled" despite them being enabled. There are no other ranking plugins that would interfere with these commands so I am not too sure why this is happening. I am running spigot on Minecraft version 1.8.x

**Comment by SirFaizdat** [comment]
Do you have Vault and an Economy plugin installed?

**Comment by xXxCrazySwaggerGamerxXx** [comment]
i have vault and when i type /prison ranks add a 0 &8[]&f it says "ranks are disabled'

please reply me at my skype account nikos.antonopoulos21

**Comment by xsehz** [comment]
there is no just "economy" plugin i am confused

**Comment by SirFaizdat** [comment]
@xXxCrazySwaggerGamerxXx  Can you check the console, there should be a reason why the ranks are disabled. Try checking the part where Prison enables.

@xsehz Economy plugins such as iConomy and Essentials, or any other economy plugin supported by Vault.

**Comment by TheFrostyNation** [comment]
The problem was that I did not have a permissions plugin installed. Installing PEX fixed the issue. Now my issue is that when I type /rankup it ranks me up to A continuously rather than going A, B, C, D, E etc.

**Comment by SirFaizdat** [comment]
@TheFrostyNation You have to set their rank IDs (sometimes the server messes this up). Use the command `/prisonranks set id <rank> <id>` to give Prison their correct order.

```
/prisonranks set id A 0
/prisonranks set id B 1
/prisonranks set id C 2
/prisonranks set id D 3
/prisonranks set id E 4
```

**Comment by TheFrostyNation** [comment]
I have just done that and it still continues to continuously rank me up to A and only A

**Comment by SirFaizdat** [comment]
@TheFrostyNation Continuous rank-up is now considered an urgent bug, and its main issue is #165.

**For future people who have this problem:** 
Ranks disables because a plugin it needs is missing. Ranks needs Vault, a permissions plugin (such as PermissionsEx), and an economy plugin (such as Essentials or iConomy). If it does not, then it will disable itself to avoid breaking anything. Once you add the missing plugin, and restart the server, ranks will enable.

**Comment by xsehz** [comment]
now i can get it working but when i try to load ranks in pex it says i dont have enough permissions even though i am in the owner group

**Comment by xsehz** [comment]
please redirect me if i am in the wrong section for this

**Comment by SirFaizdat** [comment]
@xsehz You are, but I can help :) Add the permission `permissions.manage.*` to yourself from console (that gives you access to PermissionsEx).

**Comment by xsehz** [comment]
thank you
