### ISSUE TITLE
Ranks disabled?

### ISSUE THREAD

**Issue by Endozoso** [SirFaizdat/Prison#172]
It said the ranks are disabled,even though i enabled ranks when i did /prisonranks and it said that it is disabled,even though it is enabled,can someone plz help me,i am using a rank plugin for my prison staff called power ranks,mabye that could be the problem?

**Comment by SirFaizdat** [comment]
Do you have Vault, a permissions plugin, and an economy plugin installed?

**Comment by Endozoso** [comment]
i just got accentials permissions plugin,iconomy (just got that) and vault

**Comment by SirFaizdat** [comment]
Sorry for the lack of response, this got burried under the other tickets :(
I'm going to close this, assuming that you've solved the issue or moved on. If you still have the problem and/or are still looking to fix it, please re-open this.
