### ISSUE TITLE
Change the /as Command 

### ISSUE THREAD

**Issue by Tjockototo** [SirFaizdat/Prison#173]
So im having a problem with the /as command

I have a Prison plugin which uses autosmelt that also uses /as

how do i change the command?

**Comment by SirFaizdat** [comment]
Did you try disabling Autosmelt in the configuration?

**Comment by Tjockototo** [comment]
Yes

**Comment by Tjockototo** [comment]
It sais Autosmelt is disabled when i do /as, it wont get removed, thx for answering btw ;)

**Comment by Tjockototo** [comment]
This is the Prison plugin: https://www.spigotmc.org/resources/prison.1223/

**Comment by SirFaizdat** [comment]
Here's a quick fix for you while I work on an update to fix this:

1. Open up the plugin JAR file using WinRar or another similar archiving program. 
2. Open the plugin.yml file. 
3. Replace the contents with [this](http://hastebin.com/nohocaluqi.sm)

**Comment by Camouflage100** [comment]
This is a lower priority than other bugs currently.

**Comment by SirFaizdat** [comment]
It's still a bug and deserve the label.

**Comment by Camouflage100** [comment]
Oops didn't mean to remove it. #BlameCamo

**Comment by Camouflage100** [comment]
Can't really be dealt with without adding a second download file that removes the command from the plugin.yml file. If it needs to be done; we'll start adding a second file on GitHub for people that want the autosmelt command removed from the plugin.
