### ISSUE TITLE
"Can't find world" Prison 2 Plugin

### ISSUE THREAD

**Issue by star6122** [SirFaizdat/Prison#174]
Hi!
I am trying to create a prison server and the Prison 2 plugin has been working great! My only problem is that some of the mines won't reset and when I try to manually reset them, it prints "Failed to reload <mine>. Check the console for details." The console prints, "[Prison] Did not reset mine <mine> because the world it is in could not be found." When I am in the world standing right next to it trying to reset the mine manually. Any help would be appreciated!
Thanks in advance!

**Comment by SirFaizdat** [comment]
Urgent bug! I'm looking into it now.

**Comment by star6122** [comment]
Is there an ETA on the fix?
Thanks!

**Comment by SirFaizdat** [comment]
I don’t know, because my schedule is busy and unpredictable all month. I’ll try to start fixing it today though!

**Comment by SirFaizdat** [comment]
Merging this with #161
