### ISSUE TITLE
Ranks disabled in Prison?

### ISSUE THREAD

**Issue by KazOfficial** [SirFaizdat/Prison#176]
Hello, I am Kaz, and this strange error keeps on popping up when I do /prisonranks promote KazOfficial

It shows: 
KazOfficial has been promoted to [B]!
Ranks are disabled.

Any suggestions? This is getting annoying.

**Comment by SirFaizdat** [comment]
Does it still promote you as expected? If not, then are there any errors in the console?

**Comment by SirFaizdat** [comment]
Is this issue still active?

Does it promote you as expected? If not, then are there any errors in game or in console?

**Comment by Camouflage100** [comment]
As stated many many many times before; we're redesigning the ranks system. Until then we can't really help that the system is flawed. The new system will be released in either the 2.3 or 3 release.
