### ISSUE TITLE
Really need help fast

### ISSUE THREAD

**Issue by Robslayer** [SirFaizdat/Prison#178]
Okay, so i got ur prison plugin, and how do u make like mine b a warp? because when i do /rankup, it doesnt create a warp for the next rank or anything, and instead of /rankup changing ur rank can u just make it so when a player does /rankup, it issues a manuadd <player> then the warps name command? if you know what i mean,  but basically, im having a hard time on how to set up warps 

please reply back, thanks

**Comment by Lmmb74** [comment]
Man, there is no warps included. You should setup essentials warps and make every rank to receive the essentials.warp."name" permission. If you would like to create a menu that displays the available warps, use DeluxeMenus plugin.
