### ISSUE TITLE
I hate this bug D: 

### ISSUE THREAD

**Issue by LuckyLuckiest** [SirFaizdat/Prison#179]
Hey!

I want to ask you about a bug ?

I think that it is a bug!

When you rankup from rank [K] (This is a example) {This is first rank}

This is after more ranks, like 10 more

To rank [FREE] (This is a example too) {This is the last rank}

You can rankup again to rank [K], it means that it wont stop u when u want to rank [FREE].

Please fix it D:

**Comment by SirFaizdat** [comment]
Can you be more descriptive? I am confused.

**Comment by LuckyLuckiest** [comment]
I deleted this plugin and reinstall it again, I deleted the Prison files, to make it work!
And what do I mean, I created rank [K] as the begging rank, and a made alot more ranks like J-FREE
In Rank Free (The last rank) I did /rankup again, it changed me back to rank K
It didn't say that Im in highest rank!
So I suggest doing
/prisonranks create [K] start &8[&3K&8] 100000
This is a example
/prisonranks create (rankname) (level) (prefix) (money)
level allows me to make the rank first rank or last rank or middle rank
Like changing start with [finish] and middle [mid] starting [start]
Please say that you understand me

**Comment by Camouflage100** [comment]
As stated many many many times before; we're redesigning the ranks system. Until then we can't really help that the system is flawed. The new system will be released in either the 2.3 or 3 release.
