### ISSUE TITLE
How am i supposed to list ranks?

### ISSUE THREAD

**Issue by Robslayer** [SirFaizdat/Prison#180]
when i type /ranks, it says internal error occured while attempting to perform this command, and it only started saying this after i removed a rank by doing /pranks remove then a rank?

**Comment by Camouflage100** [comment]
What error(s) are you getting on the console?

**Comment by Camouflage100** [comment]
As stated many many many times before; we're redesigning the ranks system. Until then we can't really help that the system is flawed. The new system will be released in either the 2.3 or 3 release.
