### ISSUE TITLE
Rank bugg

### ISSUE THREAD

**Issue by xPolicePrisonServer** [SirFaizdat/Prison#181]
hello, I hate this bug I have done all ranks , but when I'm in rank a and when I rank up , I get the default then when I rank up again so will I c then when I would have been B From a So I became the default , please help me!

**Comment by Camouflage100** [comment]
What permissions plugin are you using? Could be the problem

**Comment by Camouflage100** [comment]
As stated many many many times before; we're redesigning the ranks system. Until then we can't really help that the system is flawed. The new system will be released in either the 2.3 or 3 release.
