### ISSUE TITLE
More than 1 ladder.

### ISSUE THREAD

**Issue by Reeeeestyle** [SirFaizdat/Prison#184]
Is it possible to have more than one ladder?

**Comment by Camouflage100** [comment]
Can you explain what you're asking in more detail pleas

**Comment by Reeeeestyle** [comment]
Like Could I have A-B-C-D-E
And then Member-Trusted-WellKnown

**Comment by SirFaizdat** [comment]
That's something for your permissions plugin. Prison ignores ladders and just moves the player to the next rank in the list (i.e. the one with the next ID). PermissionsEx allows ladders.
