### ISSUE TITLE
Use branches for development versions

### ISSUE THREAD

**Issue by RoboMWM** [SirFaizdat/Prison#185]
Hi,
It'd probably be best to commit untested/developmental versions to a separate branch, as the current commit (at the time of creating this issue) results in the plugin spewing errors on start, and not loading any mines. Those of us who compile plugins manually would appreciate it. Thanks in advance.

**Comment by SirFaizdat** [comment]
We'll definitely do that after the latest changes are released. Thanks for bringing this to hour attention. :)
