### ISSUE TITLE
Rank Commands Not Working

### ISSUE THREAD

**Issue by sauceadmiral** [SirFaizdat/Prison#187]
I'm using Prison version 2.2.3 downloaded from Bukkit, running a Spigot 1.10.2 server. Using any rank-related commands (/pranks, /rankup, etc.) gives the message "Ranks are disabled." In the config, ranks are set to true and all other plugin features work fine. Please help?

**Comment by Jellowazza** [comment]
Yeah I have the same issue, hopefully an easy fix!

**Comment by Camouflage100** [comment]
As said before many times, the ranks system is flawed a lot. A "fixed" version of the rank system will come in v2.3.
