### ISSUE TITLE
Ranks/Ranking

### ISSUE THREAD

**Issue by eepgaming** [SirFaizdat/Prison#188]
I have the latest version.

But when i do /rankup, it either goes from the default rank to '2' (I have ranks 1 and 2) or to '1', but when you /rankup again, it keeps saying you ranked up to 1.

Please help.

**Comment by eepgaming** [comment]
It also doesn't change the prefix of the pex rank in chat? 


( I'm using 1.9 )

**Comment by DMP9-MC** [comment]
Potential solution at #193
