### ISSUE TITLE
Prefix/Suffix

### ISSUE THREAD

**Issue by MattCSPlays** [SirFaizdat/Prison#190]
I got this plugin and so far its worked great! but it says you have to have Group Manager and Vault So I got those and then after that I focused on my spawn and when I went to make Rank A I make the code for the prefix and prefix wont work but I didn't want a prefix I wanted a suffix which goes at the end of your name I saw it didn't have it so please add it and make it work because the prison wont work if I cant have the prefix and suffix thank you.

**Comment by DMP9-MC** [comment]
Is this issue resolved? If so, please close it. If not, I will be happy to assist you.

**Comment by DMP9-MC** [comment]
We don't offer support for GroupManager. Suffixes are part of GroupManager, not Prison. Check your GroupManager installation. Thanks
