### ISSUE TITLE
The rank must be loaded into PermissionsBukkit first.

### ISSUE THREAD

**Issue by HappyTG** [SirFaizdat/Prison#192]
I am trying to create a rank on my server and it won't let me. I type "/pranks add a 0" but it just says "The rank must be loaded into PermissionsBukkit first." How do I do that?

**Comment by SirFaizdat** [comment]
Prison uses groups from your permissions plugin to create ranks (this will be changed in the near future). You must create the group 'a' in your permissions plugin, which is in this case PermissionsBukkit, in order to then add the rank to Prison.
