### ISSUE TITLE
mines wont work

### ISSUE THREAD

**Issue by fisnaihd** [SirFaizdat/Prison#194]
i selected the mine using worledit, set up the blocks percentage and everything but once i reset the mine it only creates the top layer it does not add the blocks anywhere else. The mine is selected about 30 blocks down so its not a worldedit problem, anyone else had the same issue?

**Comment by DMP9-MC** [comment]
I don't think this issue has been submitted before. Can you attach your mine files for inspection?

**Comment by fisnaihd** [comment]
I found the problem, i had the mine already filled with stone. Apparently
it only works when the mine is empty

**Comment by DMP9-MC** [comment]
Good job. Please close this issue so we can keep the issue page as clean as possible.
