### ISSUE TITLE
Config Files Reset to Default

### ISSUE THREAD

**Issue by ShockShore** [SirFaizdat/Prison#202]
I tried to edit my config file but after that, when I reloaded my server, the config files were reset to it's default settings!

**Comment by DMP9-MC** [comment]
Yeah we're aware of this. This will be fixed in Version 2.4

**Comment by ShockShore** [comment]
Thank You!

**Comment by DMP9-MC** [comment]
Issues that haven't been properly resolved (ie a bug hadn't been fixed yet) shouldn't be closed until it has been resolved by a member of the prison team.

**Comment by DMP9-MC** [comment]
This has already been fixed but hasn't been released yet. Hang tight until 2.4. Enjoy your day :)

**Comment by KingKule** [comment]
DMP9-MC that's what happens to me to when i was trying to fix the Public broadcast. when will 2.4 be out?

**Comment by DMP9-MC** [comment]
Prison 2.4 should be ready this weekend and Prison 3 releases the following week
