### ISSUE TITLE
Ranks are broke again

### ISSUE THREAD

**Issue by shadowcaptain21** [SirFaizdat/Prison#203]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### What's the problem?
Ranks are broke. I'm rank K the next rank should J but when I rankup it said don't have enough money to rankup to A. It happens before tho pls fix it. No console errors.

### How do we recreate the problem?

idk

### Anything else you need to tell us?

Additional info...

**Comment by DMP9-MC** [comment]
Lack of information here. What economy plugin are you using?

**Comment by shadowcaptain21** [comment]
I use essential economy and I use group manager

**Comment by DMP9-MC** [comment]
Hmm. Can you please send me all of your rank files? (preferably in a ZIP file)

**Comment by shadowcaptain21** [comment]
Ummm I'm trying to download zip 7-zip that could zip my ranks folder but it can't it's just a fake zipper is there anything I could post here the ranks folder or could you atleast fine me a correct app for making zip folder thx

**Comment by DMP9-MC** [comment]
If you're on windows you should be able to select all your rank files (in
explorer) and right click Send to > Compressed ZIP Folder

If you can't do the above,I recommend 7-Zip. Make sure you get the one from
https://7-zip.org/

**Comment by shadowcaptain21** [comment]
[ranks.zip](https://github.com/SirFaizdat/Prison/files/779022/ranks.zip)

**Comment by shadowcaptain21** [comment]
there it is thx for the 7-zip link so that why 7-zip didnt work for me when i try to install it cuz i got winwar install i did just uninstall winwar for it to work..

**Comment by DMP9-MC** [comment]
Okay your IDs seem to be a little off. Can you please tell me the order in which you wish to rank up?

**Comment by shadowcaptain21** [comment]
the first rank is j next i,h,g,f,e,d,c,b,a,free and the last is wizard thx

**Comment by DMP9-MC** [comment]
Okay. I'm not at home anymore so I'll fix this later :)

**Comment by DMP9-MC** [comment]
The price you provided for some of the ranks are too big and are appearing as 1.0E8. You need to lower the price for C, B, A, FREE and WIZARD.
