### ISSUE TITLE
Server hangs when plugin loads

### ISSUE THREAD

**Issue by RoboMWM** [SirFaizdat/Prison#204]
### What's the problem?

Server thread hangs when the plugin is being enabled.

### What's happening?

(Snippet of startup log, other plugins are enabling as usual).

```
[12:44:13] [Server thread/INFO]: [Prison] Enabling Prison v2.3
[12:44:13] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;32;22mLoaded 12 mines.[m
[12:44:13] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;32;22mMines enabled.[m
[12:44:13] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;37;22mEnabled [0;36;22mPrison v2.3[0;37;22m. Made with <3 by [0;36;22mThe Prison Team[0;37;22m.[m
[12:44:13] [Server thread/INFO]: [0;33;22m[[0;31;22mPrison[0;33;22m] [0;30;1mEnabled in 69 milliseconds.[m
```
And it just hangs there. Apparently spigot's watchdog wasn't able to figure out it was hanging for some reason.

### How do we recreate the problem?

Start server with plugin (might need already-existing mines to load).

### Anything else you need to tell us?

Running commit https://github.com/SirFaizdat/Prison/commit/8036fb379a36e9f7c82af3f29b5c78dbbfae73f7 (latest at time of posting)

**Comment by DMP9-MC** [comment]
Thanks but we are aware of this. The update we're currently working on is far from complete, therefore bugs are yet to be fixed.

**Comment by SirFaizdat** [comment]
Well I mean, if there's a bug, having the issue would make sense...

**Comment by DMP9-MC** [comment]
Considering we never made a released a version with this bug present, having an issue on the page that issues with the releases are on doesn't male sense, but who am I to argue? Its your project...

**Comment by DMP9-MC** [comment]
This issue is fixed as of commit [e91d3e3](https://github.com/SirFaizdat/Prison/commit/e91d3e3f38a9ace5df25f6a85a60ae548e79c7e9)

**Comment by RoboMWM** [comment]
> Considering we never made a released a version with this bug present, having an issue on the page that issues with the releases are on doesn't make sense, but who am I to argue? Its your project...

This is not a reviews section. This is an issue _tracker_, a place to keep track of issues with the project.

Also, you should consider using development branches when developing new features. The master branch is usually considered the "stable" branch. Just because most server owners don't manually compile plugins from source doesn't necessarily mean you should just push everything to master.

**Comment by DMP9-MC** [comment]
We create branches for feature proposals, not features which are 100% on our to-do list.

**Comment by MiniDigger** [comment]
lets me just drop this here, maybe someone finds it useful. it explains how to properly use git: https://www.atlassian.com/git/tutorials/comparing-workflows

**Comment by DMP9-MC** [comment]
@MiniDigger thanks, but we don't particularly need tips on our development style

**Comment by SirFaizdat** [comment]
@MiniDigger Thanks for the resource, we'll try to implement this in our workflow :)
