### ISSUE TITLE
Removing all the public informationn

### ISSUE THREAD

**Issue by KingKule** [SirFaizdat/Prison#206]
I've been searching Thure the Whole plugin but i can't find out how i remove theese following publick announcments:
- Rankup
- Mines Reseting in <mins>
How can i get this removed or so it only shows up in that spesific world(s)?

I got PerWorldPlugins and PerWorldChat+

**Comment by DMP9-MC** [comment]
Simply turn 'multiworld' on in the config and enter all the worlds you wish the announcements to be sent to.
