### ISSUE TITLE
Ranks -.-

### ISSUE THREAD

**Issue by MikaelMart** [SirFaizdat/Prison#207]
so i downloaded this plugin and it seemed everything was alright the mines work everything works but then... when i try to add ranks it says "Rank are deisabled" so yeah.. i dont really know how to setup rank stuff and yea do i need Group Manager or PEX or what do i need?

**Comment by DMP9-MC** [comment]
You need a permissions plugin to use Prison Ranks. It automatically disabled if one isn't detected. Vault is compatible with Permissions 3, bPermissions, PEX, GroupManager, PermissionsBukkit, zPermission, SimplyPerms, Privileges, DroxPerms, and xPerms.

**Comment by iiNinetales** [comment]
Im also having the same issue but only when i do /pranks demote <user>

**Comment by DMP9-MC** [comment]
You most likely have an invalid rank setup. If you send me your rank files (the ones ending with `.RANK`) i can attempt to fix your issue.

**Comment by iiNinetales** [comment]
@DMP9-MC Silly question but when is Prison 3 coming out 1 place is says 19th march another place it said 26th? and is there any documentation on it anywhere too??

**Comment by DMP9-MC** [comment]
@iiNinetales Well right now I'm pretty sure Prison 3 is not releasing on either of those dates 😆 and there's a little bit of documentation over at https://github.com/MC-Prison/Prison/wiki

**Comment by TheSaltySandwich** [comment]
Please help i am having the same exact problem with the ranks are disabled but they aren't could somebody please help me?

**Comment by DylanFPS** [comment]
@TheSaltySandwich check the logs and config to see if ranks has any problems

**Comment by DylanFPS** [comment]
Closed because:
- Inactivity
- New update has come out
- This is not a question section, please consult documentation (or [watch this](https://www.youtube.com/watch?v=6rEK0h3swbw))
