### ISSUE TITLE
Permissions for Mines

### ISSUE THREAD

**Issue by Reintheoretisch** [SirFaizdat/Prison#211]
### What's the problem?

Players can't mine in the mines.

### What's happening?

No messages in the console. Do I need to give a certain permission?

### How do we recreate the problem?

I am not sure how to recreate this.

Probably something obvious I am missing...

Thanks for the help in advance!

**Comment by DylanFPS** [comment]
Please check that you don't have plugins such as WorldGuard interfering with the mines. Unless you're using Prison 3, there's no built in mine guarding. If you are using Prison 3, this is the wrong place to report the bug and you should report it [here](https://github.com/MC-Prison/Prison).

**Comment by Reintheoretisch** [comment]
I have found the issue, EssentialsProtect was messing it up.
Thank you for your help :-)
