### ISSUE TITLE
Please help me fix the error

### ISSUE THREAD

**Issue by Zkx69** [SirFaizdat/Prison#212]
https://pastebin.com/KdLtqh5A

**Comment by DylanFPS** [comment]
This is most likely an essentials/vault issue - try reinstalling it. For
some reason essentials is still loading when Prison is loading -- when
we've made it impossible to replicate such problem.

Try other plugins that use Vault/Essentials economy and if they don't work,
submit an issue in the vault repository and see what they can do.

**Comment by Zkx69** [comment]
I just checked the plugins folder and noticed that I had both the updated and outdated vault. It was actually my bad haha. Thanks for the help still and gl with your plugin !
