### ISSUE TITLE
"Item manager isn't loading"

### ISSUE THREAD

**Issue by Samlitz** [SirFaizdat/Prison#214]
If you are making a bug report, fill out the form below. If you are making a suggestion or something other than a bug report, then you may remove this boilerplate text.

### What's the problem?

I am trying to add blocks to a mine, and it gives me the error above.
### What's happening?

I used the command /mines addblock mine1 stone 90, and nothing other than the error above shows in console.
### How do we recreate the problem?

Just create that mine and try to add blocks, if it helps, the mine is 5508 blocks
### Anything else you need to tell us?

Nope

**Comment by Camouflage100** [comment]
Hey,

Currently, we are not handling v2 issues as our team is currently back in development with working on v3. We'll be releasing Prison v3 Beta 2 as soon as we fix a few bugs and add some more features. 

Thanks,
Cameron W.
