### ISSUE TITLE
AutoSmelt glitch

### ISSUE THREAD

**Issue by SaahilM** [SirFaizdat/Prison#59]
When I do /as everything works fine. It even says autosmelt has been enabled/disabled. However, this doesn't take effect in the game. It still autosmelts no matter what. However, when its been marked 'enabled', it won't show the particle effects. When 'disabled' it show particle effects and still autosmelts.

**Comment by SirFaizdat** [comment]
Remove the prison.autosmelt.auto permission from the groups.
