### ISSUE TITLE
Rankup Issue | Urgent!!!

### ISSUE THREAD

**Issue by mohitnysa** [SirFaizdat/Prison#60]
Hello! I am using your plugin and i have a problem with ranking up i followed the steps on your bucket page but it doesn't seem to work. First I Added Rank a Using Group Manager. Gave It Its Perms Then I Added It To The Prison Ranking System Then I Created B The Same As I Did With And Then I Tested /rankup And It Kept On promoting me to A for some reason... It Just Wouldn't Promote Me To Rank B.. Here Are Some Screenshots of what i did. I Even Tried Self Promoting Myself w/ the command but it kept on promoting me to A no matter what..

![2015-01-06_06 34 13](https://cloud.githubusercontent.com/assets/10417079/5627964/623552d6-956e-11e4-8df9-8eab44b76c80.png)

![2015-01-06_06 34 17](https://cloud.githubusercontent.com/assets/10417079/5627968/6a4b5e84-956e-11e4-9914-c68f66115f6e.png)

![2015-01-06_06 34 05](https://cloud.githubusercontent.com/assets/10417079/5627973/70fd48f0-956e-11e4-88fb-0f7aa43ba1de.png)

**Comment by mohitnysa** [comment]
Please Help Quick I Need My Server Done As Soon As Possible!

**Comment by mohitnysa** [comment]
I Also Made Myself Rank B And Tried Ranking Up It Said That I Was The Highest Rank Possible

**Comment by SirFaizdat** [comment]
Send me your complete permissions.yml.

**Comment by SirFaizdat** [comment]
Sorry for the delay, I've been sick xD

**Comment by mohitnysa** [comment]
permissions?

**Comment by mohitnysa** [comment]
Well

**Comment by mohitnysa** [comment]
I Use GM So I Have Like A Bunch of Worlds With Different Groups and All

**Comment by mohitnysa** [comment]
My Permissions.yml is Empty

**Comment by mohitnysa** [comment]
Ill Just put The Permissions For The Prison World.. Haven't Really Set Em Up Yet

**Comment by mohitnysa** [comment]
Don't Really Have Any Perms

**Comment by mohitnysa** [comment]
# Group inheritance
#
# Any inherited groups prefixed with a g: are global groups
# and are inherited from the GlobalGroups.yml.
#
# Groups without the g: prefix are groups local to this world
# and are defined in the this groups.yml file.
#
# Local group inheritances define your promotion tree when using 'manpromote/mandemote'

groups:
  A:
    default: true
    permissions:
    - essentials.warp.a
    - essentials.warp.shops
    - essentials.warps.a
    - essentials.warps.shops
    inheritance: []
    info:
      prefix: '&0&l[&6&lA&0&l]&r'
      build: false
      suffix: ''
  headmod:
    default: false
    permissions:
    - '*'
    inheritance:
    - admin
    info:
      prefix: ''
      build: false
      suffix: ''
  Admin:
    default: false
    permissions: []
    inheritance:
    - moderator
    - g:groupmanager_admin
    - g:bukkit_admin
    - g:essentials_admin
    - g:towny_admin
    - g:vanish_admin
    info:
      prefix: '&c'
      build: true
      suffix: ''
  free:
    default: false
    permissions: []
    inheritance:
    - z
    info:
      prefix: '&0&l[&6&lFree&0&l]&r'
      build: false
      suffix: ''
  Builder:
    default: false
    permissions: []
    inheritance:
    - default
    - g:essentials_builder
    - g:towny_builder
    info:
      prefix: '&a[Builder]'
      build: true
      suffix: ''
  f:
    default: false
    permissions: []
    inheritance:
    - e
    info:
      prefix: ''
      build: false
      suffix: ''
  Default:
    default: false
    permissions:
    - -bukkit.command.kill
    inheritance:
    - g:groupmanager_default
    - g:bukkit_default
    - g:essentials_default
    - g:towny_default
    info:
      prefix: '&e'
      build: false
      suffix: ''
  Owner:
    default: false
    permissions:
    - -vanish.*
    - '*'
    inheritance:
    - admin
    info:
      prefix: '&4'
      build: true
      suffix: ''
  g:
    default: false
    permissions: []
    inheritance:
    - f
    info:
      prefix: ''
      build: false
      suffix: ''
  d:
    default: false
    permissions: []
    inheritance:
    - c
    info:
      prefix: '&0&l[&6&lD&0&l]&r'
      build: false
      suffix: ''
  e:
    default: false
    permissions: []
    inheritance:
    - d
    info:
      prefix: '&0&l[&6&lE&0&l]&r'
      build: false
      suffix: ''
  b:
    default: false
    permissions: []
    inheritance:
    - a
    info:
      prefix: '&0&l[&6&lB&0&l]&r'
      build: false
      suffix: ''
  c:
    default: false
    permissions: []
    inheritance:
    - b
    info:
      prefix: '&0&l[&6&lC&0&l]&r'
      build: false
      suffix: ''
  n:
    default: false
    permissions: []
    inheritance:
    - m
    info:
      prefix: '&0&l[&6&lN&0&l]&r'
      build: false
      suffix: ''
  o:
    default: false
    permissions: []
    inheritance:
    - n
    info:
      prefix: '&0&l[&6&lO&0&l]&r'
      build: false
      suffix: ''
  l:
    default: false
    permissions: []
    inheritance:
    - k
    info:
      prefix: '&0&l[&6&lL&0&l]&r'
      build: false
      suffix: ''
  m:
    default: false
    permissions: []
    inheritance:
    - l
    info:
      prefix: ''
      build: false
      preifx: '&0&l[&6&lM&0&l]&r'
      suffix: ''
  j:
    default: false
    permissions: []
    inheritance:
    - i
    info:
      prefix: '&0&l[&6&lJ&0&l]&r'
      build: false
      suffix: ''
  k:
    default: false
    permissions: []
    inheritance:
    - j
    info:
      prefix: '&0&l[&6&lK&0&l]&r'
      build: false
      suffix: ''
  h:
    default: false
    permissions: []
    inheritance:
    - g
    info:
      prefix: '&0&l[&6&lH&0&l]&r'
      build: false
      suffix: ''
  i:
    default: false
    permissions: []
    inheritance:
    - h
    info:
      prefix: '&0&l[&6&lI&0&l]&r'
      build: false
      suffix: ''
  w:
    default: false
    permissions: []
    inheritance:
    - v
    info:
      prefix: '&0&l[&6&lW&0&l]&r'
      build: false
      suffix: ''
  v:
    default: false
    permissions: []
    inheritance:
    - u
    info:
      prefix: '&0&l[&6&lV&0&l]&r'
      build: false
      suffix: ''
  u:
    default: false
    permissions: []
    inheritance:
    - t
    info:
      prefix: '&0&l[&6&lU&0&l]&r'
      build: false
      suffix: ''
  t:
    default: false
    permissions: []
    inheritance:
    - s
    info:
      prefix: '&0&l[&6&lT&0&l]&r'
      build: false
      suffix: ''
  s:
    default: false
    permissions: []
    inheritance:
    - r
    info:
      prefix: '&0&l[&6&lS&0&l]&r'
      build: false
      suffix: ''
  r:
    default: false
    permissions: []
    inheritance:
    - q
    info:
      prefix: '&0&l[&6&lR&0&l]&r'
      build: false
      suffix: ''
  q:
    default: false
    permissions: []
    inheritance:
    - p
    info:
      prefix: '&0&l[&6&lQ&0&l]&r'
      build: false
      suffix: ''
  p:
    default: false
    permissions: []
    inheritance:
    - o
    info:
      prefix: '&0&l[&6&lP&0&l]&r'
      build: false
      suffix: ''
  Moderator:
    default: false
    permissions: []
    inheritance:
    - builder
    - g:groupmanager_moderator
    - g:bukkit_moderator
    - g:essentials_moderator
    - g:towny_moderator
    - g:vanish_moderator
    info:
      prefix: '&5'
      build: true
      suffix: ''
  Head-Admin:
    default: false
    permissions: []
    inheritance: []
    info:
      prefix: '&4&l[&6&lHead-Admin&4&l]'
      build: false
      suffix: ''
  z:
    default: false
    permissions: []
    inheritance:
    - y
    info:
      prefix: '&0&l[&6&lY&0&l]&r'
      build: false
      suffix: ''
  y:
    default: false
    permissions: []
    inheritance:
    - x
    info:
      prefix: '&0&l[&6&lY&0&l]&r'
      build: false
      suffix: ''
  x:
    default: false
    permissions: []
    inheritance:
    - w
    info:
      prefix: '&0&l[&6&lX&0&l]&r'
      build: false
      suffix: ''

**Comment by SirFaizdat** [comment]
It's an issue with your PermissionsEx setup. I'll do some testing for you.

**Comment by mohitnysa** [comment]
I Use Group Manager :/

**Comment by mohitnysa** [comment]
And You Can Come On My Server And Fix It If You Want I'll OP u

**Comment by mohitnysa** [comment]
IP: trollcraft.on.vg
