### ISSUE TITLE
Rank Up Message in all world

### ISSUE THREAD

**Issue by H1DD3NxN1NJA** [SirFaizdat/Prison#62]
When someone does /rankup in prison people in all my other worlds like factions sees the rankup message, is there any way to stop that from happening?

**Comment by SirFaizdat** [comment]
This is currently not possible since the multi-world feature is not quite done yet. However, you could try getting PerWorldPlugins and limiting Prison to only work in your prison world.

**Comment by H1DD3NxN1NJA** [comment]
I did that as soon as I downloaded the prison plugin then I tested the
ranks when someone was on factions (we wanted to make it a server surprise)
and he saw the rank-up msg
