### ISSUE TITLE
Version reporting incorrectly

### ISSUE THREAD

**Issue by cmorda** [SirFaizdat/Prison#63]
I have version 2.1.1 installed. I am getting notifications that there is a newer version available even after I have installed the latest version. I actually installed the latest version originally (recently added a prison server). I verified that I have the newest version by running a md5sum and comparing it to the md5 on the download page. They match.

The command /prison version reports 2.1.0.1

**Comment by SirFaizdat** [comment]
I know, it was a mistake on my part. Sorry!
