### ISSUE TITLE
Could not pass event BlockBreakEvent to Prison v2.1.0.1 Error NEED HELP!

### ISSUE THREAD

**Issue by mohitnysa** [SirFaizdat/Prison#65]
Hey, its mohitnysa once again and i don't get why but, and non-op players rent able to break blocks, ANYWHERE This iS What Comes Up In The Console

(This Is From multicraft so the newest info is on the top..)

7.02 22:04:25 [Server] INFO ... 15 more
 
07.02 22:04:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:292) ~[craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
 
07.02 22:04:25 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
 
07.02 22:04:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
 
07.02 22:04:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
 
07.02 22:04:25 [Server] INFO at me.sirfaizdat.prison.mines.MinesBlockListener.onBlockBreak(MinesBlockListener.java:28) ~[?:?]
 
07.02 22:04:25 [Server] INFO Caused by: java.lang.NullPointerException
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:667) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.ServerConnection.c(SourceFile:134) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.NetworkManager.a(NetworkManager.java:157) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockDig.handle(SourceFile:8) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.PacketPlayInBlockDig.a(SourceFile:53) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerConnection.a(PlayerConnection.java:536) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerInteractManager.dig(PlayerInteractManager.java:118) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at net.minecraft.server.v1_7_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:263) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:294) ~[craftbukkit_179_beta.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
 
07.02 22:04:25 [Server] INFO org.bukkit.event.EventException
 
07.02 22:04:25 [Server] ERROR Could not pass event BlockBreakEvent to Prison v2.1.0.1

**Comment by mohitnysa** [comment]
Here All All The Plugins I have ATm

Ultimatehub,Worldedit,Installer,TimTheEnchanter,Essentials,Voxelsniper,Essentialschat,GroupManager,Essentialsanibuild,Clearlag,Hub,vault,plotme,prison,serverlistmotd,Holographicdisplays,Multiverse-core,multiverse-portas,Commandwatcher,essentialsspawn, and protocolib..

**Comment by mohitnysa** [comment]
Please Reply Quick :)

**Comment by SirFaizdat** [comment]
That's because Prison 2.1.1 only works on spigot 1.8. Update to Spigot 1.8 or downgrade to a version before 2.1

**Comment by mohitnysa** [comment]
Thanks Man :) Fixed The problem

**Comment by SirFaizdat** [comment]
No problem ;)
