### ISSUE TITLE
Mine Restrictions Only Apply When Players Are Standing In The Mine

### ISSUE THREAD

**Issue by TheMattVid** [SirFaizdat/Prison#67]
If players are standing outside of a mine (where the blocks actually generate), players are able to mine the blocks. I was hoping that this plugin would get rid of the need for restrictions of certain groups entering mines, but this seems not to be the case.

**Comment by SirFaizdat** [comment]
Why not make the restriction area around the mine bigger? The reason why I can't add the functionality you are seeking is because if I were to do checks every time a player broke a block, there would be a lot of server lag and potential for a server crash. Another solution would be to use WorldGuard's region group restriction.

**Comment by TheMattVid** [comment]
So, if I understand correctly, this is the process that is required to make mines function as intended.
Step 1-One overall protection region over the entire mine world to prevent griefing of blocks that aren't meant to be broken.
Step 2-A region involving just the mine itself to allow breaking of all blocks in the mines.
Step 3-A larger region around the mine to restrict entrance of groups who aren't supposed to build in there.
In this situation, I may as well not even use the built-in feature that sets the groups that are allowed to build. This solution is a bit tedious and would refer to the WorldGuard group restriction feature you were referring, too.

Is there something else you are referring to when you say to make the restriction area bigger? I saw no such option in the config.

**Comment by SirFaizdat** [comment]
See the thing is, I never meant for the built-in Prison protection to be the full protection (I'm not as intelligent as Mr. Sk89q). What I would recommend is putting walls between your mines, and only having to WorldGuard group region the doorway.

**Comment by TheMattVid** [comment]
The solution is not that easy for me, since I have teleporting on my server, and I don't plan on removing it. Also, due to the fact that teleporting is on, it doesn't make much of a difference, but I have all of the mines located in the same area in the walking distance of a single warp. I have to create a protection region that protects everything around the mines, obviously so that things don't get destroyed around the mine. Then, I need to create a separate region for the mine that allows users to build because having group permissions for a certain mine does not override the protection put over the entire region. Finally, I must create slightly larger regions out of reaching distance from mines to reliably prevent players from breaking blocks in mines that they aren't supposed to have access to.

WorldGuard has the ability to effectively prevent block breaking whether someone is standing inside or outside the region. Why not add an automatic WorldGuard protection of the mine? That way, not only will owners be saved the time from creating a separate region to keep other ranks out, but they will also be saved the time from creating a region to allow users to break in the mine in the first place.

**Comment by SirFaizdat** [comment]
I guess the integration of WorldGuard could be done. I'll suggest that to the new developer (currently in the process of resigning.)

**Comment by TheMattVid** [comment]
Thanks! Can't wait for this feature to be added. It will make the plugin exponentially more usable for me.

**Comment by DMP9-MC** [comment]
Thanks for the suggestion! Just been browsing issues. That's defiantly going into consideration. Not entirely sure if I'll add it, but it is something I can add. I'll let you know on any further information.
