### ISSUE TITLE
Could not pass event BlockBreakEvent to Prison v2.1.0.1

### ISSUE THREAD

**Issue by Lahemees47** [SirFaizdat/Prison#68]
Error in console when a player breaks a block, I think it's a conflict with PrisonUtils plugin (http://dev.bukkit.org/bukkit-plugins/prisonutils/).

http://pastebin.com/4Qpr8u5u

**Comment by SirFaizdat** [comment]
Are you sure it's a conflict with PrisonUtils? If it is, try turning off PrisonUtils autosmelt (autosmelt: false), as this plugin already has that built in and this may be conflicting.

**Comment by Lahemees47** [comment]
Yes. Autosmelt is already false, but when I turned straight-to-inventory to false, then errors disappeared.

**Comment by SirFaizdat** [comment]
Good. Will mark this as a bug for the new dev to look into!

**Comment by iampyrex** [comment]
This is related to the code not being written to catch a player not having a rank that isn't assigned.
