### ISSUE TITLE
Default Ranks

### ISSUE THREAD

**Issue by TheMattVid** [SirFaizdat/Prison#70]
I, like many other people who make Prison servers, want to have starter mines that default players can use. The only problem is that default players seem to be able to use every mine until they finally perform their first rankup. The only way to include the default rank in the prisonranks part of this plugin is to include an upgrade price, so in many circumstances, players are forced to rankup before they have done anything. Also, since the rankup is going into the default rank, technically they are not ranking up at all. The whole purpose of the rankup is so that this plugin will actually recognize that they should be given permission to mine. Perhaps, if the plugin allowed for the option to choose a starter rank, I would be able to solve some flaws in the logistics of how the plugin is running.

**Comment by DMP9-MC** [comment]
This could possibly be released/fixed in 2.1.3. There's currently a poll on our BukkitDev page on what O should add next. But I will definitely take this into consideration.
