### ISSUE TITLE
no 2.1.1 update for plugin

### ISSUE THREAD

**Issue by suresttexas00** [SirFaizdat/Prison#71]
The plugin messages the console that a new version is available.  when you run /prison update, it "downloads" a new file and tells you that you need to restart/reload.  after reloading, it still says you need and update to 2.1.1.. does this over and over.

Tried manually updating from this link:
http://dev.bukkit.org/bukkit-plugins/mcprison/files/22-prison-v2-1-1/
however, that is still 2.1.0 from dec 26th at that link...

So.. NEW FILE, por favor?

**Comment by SirFaizdat** [comment]
Well there's no need to be rude. Just a simple mistake. 

Solution: Open up Prison.jar using 7zip or by changing the filename to Prison.zip. Go to the plugin.yml, and change version: 2.1.0.1 to 2.1.1.

**Comment by suresttexas00** [comment]
Not rude, just jokingly...  Thanks... so the December version IS the 2.1.1?

**Comment by SirFaizdat** [comment]
Yup
