### ISSUE TITLE
It won't let me rankup

### ISSUE THREAD

**Issue by SayHi2uTube** [SirFaizdat/Prison#72]
I have A - Z, and I am at A. When it keep trying to rank me up, it says ranked up to A everytime I try. I changed the A from $1 to 0$ but it doesn't work.

**Comment by DMP9-MC** [comment]
Hello...

Can you please send me your ranks.yml?

**Comment by SayHi2uTube** [comment]
![rankup](https://cloud.githubusercontent.com/assets/11262093/6472356/c66dbea0-c1bf-11e4-872a-f1ef6ba93000.png)
Here is the image. I tried to remove the ranks and I added them back but it didn't work. My server ip is: 192.99.13.214:43283

**Comment by DMP9-MC** [comment]
I'll join your server in the morning (UK, it's 21:16 here). I'm busy right now. But here's some things:

- Make sure your not using the 2.1.2 dev build
- If possible, send me those .rank files
- Send me the server log (/logs/latest.log)

**Comment by SayHi2uTube** [comment]
So I can't use the 2.1.2 dev build version of prison 2?

**Comment by DMP9-MC** [comment]
No. That was build in the middle of development to test our new build
server. Wait until the new version officially comes out on BukkitDev. For
now, don't instalol that dev build. It's messed up.

**Comment by SayHi2uTube** [comment]
So which one is safe? I'm on 1.7/1.8 Spigot

**Comment by DMP9-MC** [comment]
Use 2.1.1

**Comment by SayHi2uTube** [comment]
It says not found

**Comment by SirFaizdat** [comment]
He means http://dev.bukkit.org/bukkit-plugins/mcprison/files/22-prison-v2-1-1/

**Comment by DMP9-MC** [comment]
That works too... ^_^
I swear I put 2.1.1 on my website, probably just my crappy memory lol

**Comment by DMP9-MC** [comment]
Turns out my website was down... Derp! I checked on your server... I can
come on again if you wish
