### ISSUE TITLE
Prison 2 Permissions Error

### ISSUE THREAD

**Issue by Xysche** [SirFaizdat/Prison#73]
I currently have prison 2.1.1 installed on my Spigot 1.8 server and am having issues with permissions. In a nutshell, I am fairly well versed in coding GroupManager however the permissions for Prison 2 don't seem to actually grant any in-game abilities. I am able to /block and /autosmelt so I know prison itself is functioning, however the mines/ranks commands don't seem to be working. I have the permissions currently coded as:
 - prisons.ranks.manage
 - prisons.mines.manage

Currently running GroupMan, Vault, WordEdit - all up-to-date, among others.

Thanks!

**Comment by DMP9-MC** [comment]
Can you please send me your GroupManager permission files and/or config.yml? I need to look into this!
