### ISSUE TITLE
Warps

### ISSUE THREAD

**Issue by mslaw** [SirFaizdat/Prison#75]
The code to set warps is Set a warp by doing /pwarps setwarp <warp-name> (2.1.2+), but when i use this command it tells me that it is an unknown command.  So, I assumed that the (2.12+) might not be included in the command so i left that out, and I still got the 'unknown command' message.  

Also, how do I protect the Prison spawn? and the area around the Spawn other than the mines from anyone breaking blocks? or, does the spawn need to go in a different world?  I made a cavern and put the mines down there but how do i prevent the players from breaking blocks from areas other than the actual mine? Sorry to be so dumb, but I am new to this plugin.

**Comment by SirFaizdat** [comment]
The pwarps command has been temporarily removed. Also, check out WorldGuard (http://dev.bukkit.org/bukkit-plugins/worldguard/). It can protect certain regions of the world so that normal players can't break it.

**Comment by mslaw** [comment]
Thank you SirFaizdat.  If we do not use /pwarp then what do we use to get players to the mine from the lobby? 

And I am familiar with regions but within the region would be the mines so they would need to be able to mine but not break blocks outside of the mine, correct? SirFaizdat do you have a server where I could see first hand how this plugin works?

**Comment by mslaw** [comment]
Wait, I only have one server which is hosted and I use multiverse, can i even use this plugin? or does it require its own server and not just a separate world.

**Comment by DMP9-MC** [comment]
Hey! We've moved to BukkitDev for tickets! Thanks,

DMP9
