### ISSUE TITLE
Unable to create rank

### ISSUE THREAD

**Issue by Oneki123** [SirFaizdat/Prison#79]
Hi,
When I try to create a rank it says 

This rank does not exist

The command im using is

/prisonranks add A 0 A

Thanks

**Comment by SirFaizdat** [comment]
Did you create the rank "A" first in your permissions plugin?

**Comment by Oneki123** [comment]
I dont have a permissions plugin yet

**Comment by SirFaizdat** [comment]
You'll need one to set up ranks, at least until Prison 3 comes out (which isn't any time soon). I recommend PermissionsEx for your permissions plugin, and if you'd like, I'll come set it up for you.

**Comment by Oneki123** [comment]
Omg Ty :) I have been looking for a permissions coder for days

**Comment by SirFaizdat** [comment]
What's your server IP? I'll come on as soon as possible.

**Comment by Oneki123** [comment]
Server is actually down right now. Im out atm sorry

**Comment by SirFaizdat** [comment]
It's fine, send it to me at your earliest convenience.
