### ISSUE TITLE
not able to create rank ladder

### ISSUE THREAD

**Issue by ChickenNuggetNG** [SirFaizdat/Prison#82]
09.09 21:42:50 [Server] INFO Owner2: ✖✖Owner✖✖ChickenNugget
09.09 21:42:46 [Server] INFO ... 14 more
09.09 21:42:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at me.sirfaizdat.prison.ranks.cmds.RanksCommandManager.onCommand(RanksCommandManager.java:83) ~[?:?]
09.09 21:42:46 [Server] INFO at me.sirfaizdat.prison.core.AbstractCommandManager.onCommand(AbstractCommandManager.java:48) ~[?:?]
09.09 21:42:46 [Server] INFO at me.sirfaizdat.prison.core.Command.run(Command.java:75) ~[?:?]
09.09 21:42:46 [Server] INFO at me.sirfaizdat.prison.ranks.cmds.CmdAddRank.execute(CmdAddRank.java:29) ~[?:?]
09.09 21:42:46 [Server] INFO at me.sirfaizdat.prison.ranks.Ranks.isRank(Ranks.java:537) ~[?:?]
09.09 21:42:46 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_PermissionsEx.getGroups(Permission_PermissionsEx.java:372) ~[?:?]
09.09 21:42:46 [Server] INFO Caused by: java.lang.NoSuchMethodError: ru.tehkode.permissions.PermissionManager.getGroupList()Ljava/util/List;
09.09 21:42:46 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:517) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:609) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:284) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:656) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_60]
09.09 21:42:46 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_60]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:919) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1058) [craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:625) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Bukkit-33d5de3]
09.09 21:42:46 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'prisonranks' in plugin Prison v2.1.3
09.09 21:42:46 [Server] ERROR null

**Comment by SirFaizdat** [comment]
Try this and see if it works:
https://www.dropbox.com/s/67zsrse9i58vmz7/Prison.jar?dl=0
It's a development build for v2.1.4 (even though it says v2.2-SNAPSHOT), and it should fix your problem. Let me know how it goes so I can push the update out to everyone :)

**Comment by AlliedCore** [comment]
Hello SirFaizdat. Its Me Allied. Add me to this project!

**Comment by SirFaizdat** [comment]
Fixed in v2.1.4 - download on the plugin page.
