### ISSUE TITLE
Prison Not Working

### ISSUE THREAD

**Issue by xJinxMC** [SirFaizdat/Prison#84]
When I download the plugin I put It In my plugins (FILE)folder and I restart my server and It doesn't load up without the plugin being green when I do /pl.
It doesn't even show up when I do it aswell

**Comment by SirFaizdat** [comment]
What version of Prison are you using?

**Comment by SirFaizdat** [comment]
Are you sure you installed all the dependencies? Make sure you have **Vault** and **WorldEdit** installed.

**Comment by xJinxMC** [comment]
I have and its not working

**Comment by SirFaizdat** [comment]
Please make sure you have the latest version of Spigot (MC 1.8.8) and Prison (v2.1.4 for MC 1.8.8).
