### ISSUE TITLE
[BUG] "That rank does not exist."

### ISSUE THREAD

**Issue by bonusunicorn** [SirFaizdat/Prison#88]
There is an issue with ranks. When you try to do the command ex: /prisonranks add c 1500 &8[&a&lC&8] it says "That rank does not exist."

**Comment by SirFaizdat** [comment]
You must create the rank "C" in your server's permissions plugin first. This will change in Prison v3.0, but until then, this is how to do it :(

**Comment by PrisonTech** [comment]
How do you do that? It gave me the same error code in the minecraft chat with "that rank doesn't exist"

**Comment by PrisonTech** [comment]
and with the whole "permissions plugin" thing. I don't know what that is

**Comment by SirFaizdat** [comment]
Permissions plugins such as PermissionsEx give players a rank with certain command permissions attached to it. Prison attaches to these ranks and moves players through them.
