### ISSUE TITLE
[Bug] Rank ups - not in order

### ISSUE THREAD

**Issue by henryaustin404** [SirFaizdat/Prison#89]
Hi, 

I have 26 ranks, from A-Z. Rank A is worth 10k, B worth 20k, C worth 30k, and so on. 

When players are in Group A or B and they do /rankup, it moves them to the next rank without an issue. However, when players are in Group C, and they do /rankup, it moves them back to Rank B. 

I have checked over configs for GM and Prison, and they seem to be in order. 

Henry

**Comment by SirFaizdat** [comment]
Can you please send me your Prison folder and your GroupManager folder in zip format?

**Comment by henryaustin404** [comment]
Config as requested: https://www.dropbox.com/s/iykgy83tpwklrvb/Config.zip?dl=1

**Comment by SirFaizdat** [comment]
I will look into this tomorrow morning (eastern daylight time), as that is the next I'll be on the computer. Until then, make sure your ranks always inherit the one before it (/mangaddi).

**Comment by henryaustin404** [comment]
Hi,

Making all groups inherit their previous group fixed the problem. Thanks for your fast reply!

**Comment by SirFaizdat** [comment]
No problem! Glad it helped :)
