### ISSUE TITLE
Mines

### ISSUE THREAD

**Issue by qwertykeyz** [SirFaizdat/Prison#91]
I made an 'A' rank with my permissions plugin (GroupManager) and I loaded it into the prison plugin. I then made a mine and named it 'A' and associated the 'A' rank with it. The only problem is, that the 'A' rank can't mine in the 'A' mine, unless I add essentials.build to their permissions, but then they can grief outside of the mine. I do not have a region surrounding the mine and the rest of the prison, the error message that comes up is, "You are not permitted to use 'item'." Or if you do break the block, you don't collect it, instead you receive, "You are not permitted to break 'block' blocks here." Please help me.

**Comment by SirFaizdat** [comment]
First, delete Essentials Antibuild and Essentials Protect. Then, get WorldGuard and configure it so that only certain ranks can build in the mine area. I don't know how to do this, but there should be plenty of tutorials online :)

**Comment by qwertykeyz** [comment]
Thank you!

**Comment by SirFaizdat** [comment]
No problem!
