### ISSUE TITLE
Prison Prefix Problem

### ISSUE THREAD

**Issue by snorting** [SirFaizdat/Prison#93]
Hi,

I've got to say, NICE PLUGIN! But i'm having an issue with the prefix display of the plugin. Whenever someone ranks up etc or does something that involves the plugin sending a message back to the player or sending it to the server, the prefix comes up funny. I have attached the picture.

Thanks!
![prefix](https://cloud.githubusercontent.com/assets/15505518/10861730/fd282cf2-7fd6-11e5-97ce-b4680cbaa91b.PNG)

**Comment by SirFaizdat** [comment]
Thanks! Which version are you running?

**Comment by snorting** [comment]
Version is 1.7.10

**Comment by SirFaizdat** [comment]
Prison v2.1.4 fixes this bug, but I'm not sure if it runs on MC 1.7.10.

**Comment by snorting** [comment]
Is there a way to make a patch at all XD

**Comment by SirFaizdat** [comment]
I honestly would if I could, but I don't have the code for that version anymore. I'm really sorry :(

I can't remember, but I think that you can set the prefix in the config. Is that true?

**Comment by snorting** [comment]
Sadly you cant change the prefix in the config, I had a look in the jar to see if there was something wrong with the colour format of how you have set it, but there was nothing to be found. It all looked fine.

**Comment by snorting** [comment]
Hi,
I updated to the latest version and it does work with 1.7.10!

Thanks for your help!
