### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by snorting** [SirFaizdat/Prison#94]
Hi,
In the config file, what does this mean:

multiworld: false
world-list: [plots, mines]

Thanks!

**Comment by SirFaizdat** [comment]
If you have multiple worlds on your server, but you only want to have one of them be for Prison, you would turn that on and set the worlds. However, I don't recommend this feature too much as it is a bit buggy.

**Comment by snorting** [comment]
Do I have to use this feature if I would like to set spawns for when the mines reset? Like do I have to set all the mine names in the config in that section I was talking about?

Because at the moment if you are in the mine and it resets you either get stuck in the wall or you get moved to the edges of the mine.

**Comment by SirFaizdat** [comment]
No, you don't have to use this feature to set mine spawns.

**Comment by snorting** [comment]
Is there anything else you need to do to set up the mines spawn? Other than execute the command, like do you need a warp or something?

**Comment by SirFaizdat** [comment]
Nope, just use the command

**Comment by snorting** [comment]
When I've set the comment, it doesnt teleport me to the spawn that I have set. Why's this?

**Comment by SirFaizdat** [comment]
Could I join the server to help?

**Comment by snorting** [comment]
At the moment I am at school, but will you be on in about 7 hours?

**Comment by SirFaizdat** [comment]
No, sorry (I'll be sleeping at that time). What version of Prison are you using?

**Comment by snorting** [comment]
The latest version.

**Comment by snorting** [comment]
The latest version does work on 1.7.10 too :)

**Comment by SirFaizdat** [comment]
Hmmm... I'll have to look into it more. The code looks fine; after typing /mines setspawn <mine> it should set the spawn location to where you're standing.

**Comment by snorting** [comment]
May I ask what timezone you are in?

**Comment by SirFaizdat** [comment]
US EST

**Comment by snorting** [comment]
How much is your offset?

**Comment by snorting** [comment]
GMT -5?

**Comment by SirFaizdat** [comment]
Yes

**Comment by snorting** [comment]
What time will you be on tomorrow in your time?

**Comment by SirFaizdat** [comment]
I'll be on from 6:30 to 7:30 AM my time, and again after 4 PM (16:00) my time

**Comment by snorting** [comment]
I can be on from 1am your time to 4pm your time.

**Comment by SirFaizdat** [comment]
Alright, I'll try to get on at 3:30 PM my time so that I have access to MC.

**Comment by snorting** [comment]
Ok, whats your ign?

**Comment by SirFaizdat** [comment]
SirFaizdat

**Comment by snorting** [comment]
Ok, tell me on here when you come online.

**Comment by snorting** [comment]
By the way, our ip is: mc.monkeycraft.us

**Comment by snorting** [comment]
Our host was down for long time, sorry if you couldnt connect to the server.

**Comment by SirFaizdat** [comment]
I came online at 5:53 PM my time (sorry, I'm like 2 hours late) and asked for you as snorting but I got no reply.

**Comment by snorting** [comment]
Sorry. Btw ask for Brushes or Haxor, as snortings is just a new alias I use. Is there any other time you will be available today? 
I am GMT+10 and have school from 8:30am to 3pm. (use world time buddy to figure out the differences and tell me what time would suit you please.)

**Comment by SirFaizdat** [comment]
Unfortunately, the next time I can be on at a time you'll be on is Friday right after you get home from school.

**Comment by snorting** [comment]
I can be on from 4pm my time to 7:45am my time

**Comment by snorting** [comment]
And on weekends, pretty much all day.

**Comment by SirFaizdat** [comment]
Does 7:10 AM tomorrow work for you?

**Comment by snorting** [comment]
My time or your time?

**Comment by SirFaizdat** [comment]
Yours

**Comment by snorting** [comment]
Yeah that will work well.

Do you have skype? As it would be easier talking on that

**Comment by SirFaizdat** [comment]
Yeah - sirfaizdat1

**Comment by snorting** [comment]
Added you.

**Comment by SirFaizdat** [comment]
Fixed in version 2.1.5.
