### ISSUE TITLE
Unknown Error?!?!

### ISSUE THREAD

**Issue by madaeq1234** [SirFaizdat/Prison#96]
Well so i just booted it up and it posted this is in the console
<img width="401" alt="2015-11-07_20-02-35" src="https://cloud.githubusercontent.com/assets/8119451/11018187/11e93226-858b-11e5-9479-10e40b720842.png">

**Comment by SirFaizdat** [comment]
What did it post?

**Comment by madaeq1234** [comment]
I just uploaded an image but i may have just figured it out but here is the pic. http://i.imgur.com/KjvwHGv.png

**Comment by madaeq1234** [comment]
It happens after i join

**Comment by SirFaizdat** [comment]
Do you have Vault, an economy plugin, and WorldEdit installed?

**Comment by madaeq1234** [comment]
Umm... I have Vault, And worldedit, and worldGuard all installed

**Comment by SirFaizdat** [comment]
Do you have Essentials?

**Comment by madaeq1234** [comment]
No but i was planning on adding it... Should I?

**Comment by madaeq1234** [comment]
Oh its fixed! Thank you!!

**Comment by madaeq1234** [comment]
(CLOSED)
