### ISSUE TITLE
A small issues

### ISSUE THREAD

**Issue by madaeq1234** [SirFaizdat/Prison#97]
I have it working and /pwarps doesn't work... Please help! I have essentials, Worldedit, Vault, Etc

**Comment by SirFaizdat** [comment]
/pwarps does not work, it is a remnant of the failed v2.1.3 (which has been removed). However, if you have Essentials installed, you can use the /setwarp and /warp commands there :)

**Comment by madaeq1234** [comment]
Ok and One last question, do the prison ranks have permissions?

**Comment by SirFaizdat** [comment]
No, you'll have to use your server's permissions plugin. However, Prison v3.0 will have a built-in permissions system.

**Comment by madaeq1234** [comment]
Ok that should be coming out this month right

**Comment by SirFaizdat** [comment]
Next month

**Comment by madaeq1234** [comment]
ok Well thank you! (CLOSED)
