### ISSUE TITLE
every time i rankup it puts me to default group

### ISSUE THREAD

**Issue by joeytheboss54** [SirFaizdat/Prison#98]
every time i am ranking from a to b it puts me back to default group it needs to put the player in to group b if you rankup to b idk why this is doing this please help me fix this thank you

**Comment by SirFaizdat** [comment]
Make sure each group inherits its predecessor in your permissions plugin. 

For example, group B inherits group A, group C inherits group B, and so on.

**Comment by joeytheboss54** [comment]
do you know the command for group manager to do it

**Comment by SirFaizdat** [comment]
```/mangaddi B A``` will make group B inherit group A.
```/mangaddi C B``` will make group C inherit group B.

And so on.

**Comment by joeytheboss54** [comment]
everytime i rankup it puts me to b everytime

**Comment by SirFaizdat** [comment]
Make sure the inheritance tree is correct.
