### ISSUE TITLE
When using /rankup...

### ISSUE THREAD

**Issue by SwagaNout297** [SirFaizdat/Prison#99]
When a certain player uses /rankup everything works fine, instead of ranking up the player stays on the same rank for example:
[B] [Member]SwagStarX: /rankup
Prison > You have ranked up to B!
Prison > SwagStarX ranked up to B!
[B] [Member]SwagStarX: um..
(instead of becoming "[C]" the player stays at the same rank he/she had..
Please help, I cant seem to find a fix for this. Thank You

Regards,
SwagStarX

**Comment by SirFaizdat** [comment]
Make sure each rank inherits the last. For example, rank B inherits A, rank C inherits B, etc.

**Comment by SwagaNout297** [comment]
oh thank you very much :D
